INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '00' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '01' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '02' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '03' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '04' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '05' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '06' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '07' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '10' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '11' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '12' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '20' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '31' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '32' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '33' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '34' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '35' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '50' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '66' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '77' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '88' 
  AND MCC.CENTER_ID = '1'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '99' 
  AND MCC.CENTER_ID = '1';


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '00' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '01' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '02' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '03' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '04' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '05' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '06' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '07' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '10' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '11' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '12' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '20' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '27' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '28' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '29' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '30' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '31' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '32' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '33' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '34' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '35' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '37' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '38' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '39' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '40' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '47' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '48' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '49' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '50' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '60' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '66' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '67' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '68' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '69' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '77' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '88' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '90' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '96' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '97' 
  AND MCC.CENTER_ID = '2'; 


INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '98' 
  AND MCC.CENTER_ID = '2'; 
 

INSERT 
INTO M_CENTER_CLASS_DTL_SUB( 
  CENTER_CLASS_DTL_ID
  , OTHER1_COMMENT
  , OTHER2_COMMENT
) 
SELECT
  MCCD.CENTER_CLASS_DTL_ID
  ,'''0'':国産未使用,''1'':国産使用'
  ,'''0'':輸入未使用,''1'':輸入使用' 
FROM
  M_CENTER_CLASS MCC 
  INNER JOIN M_CENTER_CLASS_DTL MCCD 
    ON MCC.CENTER_CLASS_ID = MCCD.CENTER_CLASS_ID 
WHERE
  1 = 1 
  AND MCC.CLASS_CD = 'DESIGNFLG' 
  AND MCCD.CLASS_DTL_CD = '99' 
  AND MCC.CENTER_ID = '2';

