-- ššš‚±‚±‚©‚ç§Œä•¶‚Ìˆ×AŒë‚Á‚ÄÁ‚³‚È‚¢‚æ‚¤’ˆÓ‚·‚éŽ–ššš
-- #df:checkEnv(ut,saas,manual)#
-- ššš‚±‚±‚Ü‚Å§Œä•¶‚Ìˆ×AŒë‚Á‚ÄÁ‚³‚È‚¢‚æ‚¤’ˆÓ‚·‚éŽ–ššš

-- #df:begin#
CREATE PROCEDURE COMMONINDEXCREATEPROC AS 

DECLARE @QRY NVARCHAR(2000); 
DECLARE @TBL NVARCHAR(200); 
DECLARE @COL NVARCHAR(200); 

BEGIN DECLARE MYCUR CURSOR FOR 
SELECT
    A.TABLE_NAME
    , A.COLUMN_NAME 
FROM
    INFORMATION_SCHEMA.COLUMNS A 
WHERE
    COLUMN_NAME = 'CONTROL_NO' 
ORDER BY
    TABLE_NAME
    , COLUMN_NAME; 

OPEN MYCUR; 

FETCH NEXT 
FROM
    MYCUR 
INTO @TBL
, @COL; 

WHILE @@FETCH_STATUS = 0 BEGIN 
SET
    @QRY = 'CREATE INDEX [' + @TBL + '_IXC] ON [' + @TBL + ']([' + @COL + ']);'; 

EXECUTE SP_EXECUTESQL@QRY; 

FETCH NEXT 
FROM
    MYCUR 
INTO @TBL
, @COL; 

END CLOSE MYCUR; 

DEALLOCATE MYCUR; 

END EXECUTE COMMONINDEXCREATEPROC; 

DROP PROCEDURE COMMONINDEXCREATEPROC;

