angular.module('oneslogiWms.Assist',
		[
		'oneslogiWms.ProductMasterSearchSD'
		,'oneslogiWms.VendorMasterSearchSD'
		,'oneslogiWms.DeliveryCourseSearchSD'
		,'oneslogiWms.DeliveryMasterSearchSD'
		,'oneslogiWms.LocationMasterSearchSD'
		,'oneslogiWms.ZipMasterSearchSD'
		 ]
);