/*
 [df:title]
 取引先マスタ一括取込一覧を取得します。

 [df:description]
  SQL Description here.

*/

-- #df:entity#

-- !df:pmb extends Paging!
-- !!Long cultureId!!
-- !!AutoDetect!!

/*IF pmb.isPaging()*/
SELECT EC.CUSTOMER_ID
	  ,EC.RECEIVE_CD
	  ,EC.RECEIVE_ROW_ID
	  ,EC.IMPORT_FLG
	  ,EC.ERROR_FLG
	  ,EC.ERROR_MESSAGE_CD
	  ,EC.CLIENT_CD
	  ,EC.CUSTOMER_CD
	  ,EC.CUSTOMER_NM
	  ,EC.CUSTOMER_ABBR
	  ,EC.VENDOR_FLG
	  ,EC.DELIVERY_FLG
	  ,EC.ONETIME_FLG
	  ,EC.DEPOSIT_FLG
	  ,EC.ZIP_CD
	  ,EC.ADDRESS1
	  ,EC.ADDRESS2
	  ,EC.ADDRESS3
	  ,EC.TEL_NO
	  ,EC.ALLOC_ORDER
	  ,EC.SHIPPING_STOP_FLG
	  ,EC.LOT_REVERSE_FLG
	  ,EC.LIMIT_DT_REVERSE_FLG
	  ,EC.CENTER_CD
	  ,EC.DELIVERY_COURSE_CD
	  ,EC.DELIVERY_ORDER
	  ,EC.DELIVERY_READTIME
	-- [C-CWMS-0060] EDI機能(汎用)バッチ化対応 2016.08.01 kawana Start
	  ,BM.MESSAGE_NM
	  ,MCL.CLIENT_ID
	  ,MCL.CLIENT_NM
	  ,MZ.ZIP_ID AS MZ_ZIP_ID
	  ,MZ.ADDRESS1 AS ZIP_ADDRESS1
	  ,MZ.ADDRESS2 AS ZIP_ADDRESS2
	  ,MZ.ADDRESS3 AS ZIP_ADDRESS3
	  ,MCE.CENTER_ID
	  ,MCE.CENTER_NM
	  ,MDC.DELIVERY_COURSE_NM AS DELIVERY_COURSE_NM
	  ,MDC.DELIVERY_COURSE_ID AS DELIVERY_COURSE_ID
	  ,MDC.VERSION_NO AS MDC_VERSION_NO
	  ,MCU.CUSTOMER_ID AS MCU_CUSTOMER_ID
	  ,MCU.VERSION_NO AS MCU_VERSION_NO
-- ELSE SELECT COUNT(*)
/*END*/
	FROM E_CUSTOMER EC
		INNER JOIN M_CLIENT MCL
			ON MCL.CLIENT_CD = EC.CLIENT_CD
		INNER JOIN M_CENTER MCE
			ON MCE.CENTER_CD=EC.CENTER_CD
			AND MCE.DEL_FLG='0'
		LEFT JOIN M_ZIP MZ
			ON MZ.ZIP_CD = EC.ZIP_CD
			AND MZ.DEL_FLG='0'
		LEFT JOIN M_DELIVERY_COURSE MDC
			ON MDC.DELIVERY_COURSE_CD= EC.DELIVERY_COURSE_CD
			AND MDC.CENTER_ID = MCE.CENTER_ID
			AND MDC.DEL_FLG='0'
		LEFT JOIN M_CUSTOMER MCU
			ON MCU.CUSTOMER_CD=EC.CUSTOMER_CD
		-- [#2142][Ver2.1.0] 荷主が正しく処理されない問題を修正  2017.07.19 miyabe Start
			AND MCU.CLIENT_ID = MCL.CLIENT_ID
		-- [#2142][Ver2.1.0] 荷主が正しく処理されない問題を修正  2017.07.19 miyabe End
		LEFT JOIN B_MESSAGE BM
			ON BM.MESSAGE_CD=EC.ERROR_MESSAGE_CD
			/*IF pmb.cultureId != null*/
			AND BM.CULTURE_ID=/*pmb.cultureId*/1
			/*END*/
	WHERE EC.RECEIVE_CD = /*pmb.receiveCd*/'WMS186'
		/*IF pmb.errorFlg != null*/
 		AND EC.ERROR_FLG=/*pmb.errorFlg*/'1'
		/*END*/
		/*IF pmb.importFlg != null*/
 		AND EC.IMPORT_FLG=/*pmb.importFlg*/'0'
		/*END*/
/*IF pmb.isPaging()*/
	ORDER BY EC.RECEIVE_CD ASC
			,EC.RECEIVE_ROW_ID ASC
			,EC.CUSTOMER_ID ASC
	 -- [C-CWMS-0060] EDI機能(汎用)バッチ化対応 2016.08.01 kawana End
/*END*/
