/*
 [df:title]
 出荷指示一括取込一覧を取得します。

 [df:description]
  SQL Description here.

*/
-- #df:entity#
-- !df:pmb extends Paging!
-- !!Long cultureId!!
-- !!AutoDetect!!
/*IF pmb.isPaging()*/
SELECT ESI_0.SHIPPING_INST_ID
	  ,ESI_0.RECEIVE_CD
	  ,ESI_0.RECEIVE_ROW_ID
	  ,ESI_0.IMPORT_FLG
	  ,ESI_0.ERROR_FLG
	  ,ESI_0.ERROR_MESSAGE_CD
	  ,ESI_0.CLIENT_CD
	  ,ESI_0.CENTER_CD
	  ,ESI_0.EMERGENCY_FLG
	  ,ESI_0.CLIENT_SHIPPING_NO
	  ,ESI_0.SUPPLY_CUSTOMER_CD
	-- [#246][2.1.0 バグ・品質向上対策] 入荷予定/出荷指示受信テーブルの物理名を(～ID)から(～CD)に修正 2016.11.22 honma Mod Start
	  ,ESI_0.PROCESS_TYPE_CD
	-- [#246][2.1.0 バグ・品質向上対策] 入荷予定/出荷指示受信テーブルの物理名を(～ID)から(～CD)に修正 2016.11.22 honma Mod End
	  ,ESI_0.DELIV_PLAN_DT
	  ,ESI_0.WORK_DT
	  ,ESI_0.SHIPPING_DT
	  ,ESI_0.DELIVERY_COURSE_CD
	  ,ESI_0.DELIV_DT
	  ,ESI_0.DELIV_TZ
	  ,ESI_0.DELIV_CUSTOMER_CD
	  ,ESI_0.DELIV_CUSTOMER_NM
	  ,ESI_0.DELIV_ZIP_CD
	  ,ESI_0.DELIV_ADDRESS1
	  ,ESI_0.DELIV_ADDRESS2
	  ,ESI_0.DELIV_ADDRESS3
	  ,ESI_0.DELIV_TEL_NO
	  ,ESI_0.DELIV_ADDRESS_SUPPLY
	  ,ESI_0.PICKING_WORK_MESSAGE
	  ,ESI_0.PRODUCT_CD
	  ,ESI_0.PRODUCT_NM
	  ,ESI_0.DEPOSIT_CD
	  ,ESI_0.STOCK_TYPE_CD
	  ,ESI_0.INST_NUM
	  ,ESI_0.LOT
	  ,ESI_0.LIMIT_DT
	  ,ESI_0.WAREHOUSE_CD
	  ,ESI_0.LOCATION_CD
	  ,ESI_0.DEL_FLG
	  ,ESI_0.VERSION_NO
	  ,ESI_0.CONTROL_NO
	  ,ESI_0.ADD_DT
	  ,ESI_0.ADD_USER
	  ,ESI_0.ADD_PROCESS
	  ,ESI_0.UPD_DT
	  ,ESI_0.UPD_USER
	  ,ESI_0.UPD_PROCESS
	  ,MC_0.CLIENT_ID
	  ,MC_0.CLIENT_CD
	  ,MCT_0.CENTER_ID
	  ,MCT_0.CENTER_CD
	  ,DFLOC_0.CUSTOMER_ID AS SUPPLY_CUSTOMER_ID
	  ,DFLOC_0.CUSTOMER_NM AS SUPPLY_CUSTOMER_NM
	  ,DFLOC_0.CUSTOMER_ABBR AS SUPPLY_CUSTOMER_ABBR
	  ,MDC_0.DELIVERY_COURSE_NM,MP_0.PRODUCT_ID
	  ,MP_0.PRODUCT_NM AS MP_PRODUCT_NM
	  ,MP_0.PRODUCT_ABBR
	  ,MP_0.JAN_CD
	  ,MP_0.LOT_MANAG_FLG  -- // cls(LotManagFlg)
	  ,MP_0.LIMIT_DT_MANAG_FLG  -- // cls(LimitDtManagFlg)
	  ,DFLOC_1.CUSTOMER_ID AS DELIV_CUSTOMER_ID
	  ,DFLOC_1.CUSTOMER_NM AS ONE_CUSTOMER_NM
	  ,DFLOC_1.ZIP_CD
	  ,DFLOC_1.ADDRESS1
	  ,DFLOC_1.ADDRESS2
	  ,DFLOC_1.ADDRESS3
	  ,DFLOC_1.TEL_NO
	  ,DFLOC_1.ONETIME_FLG  -- // cls(OnetimeFlg)
	  ,MPT.PROCESS_TYPE_ID AS MPT_PROCESS_TYPE_ID
	-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana Start
	  ,VD_0.DICT_NM AS PROCESS_TYPE_NM
	  ,VD_1.DICT_NM AS STOCK_TYPE_NM
	-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana End
	  ,MST.STOCK_TYPE_ID AS MST_STOCK_TYPE_ID
	  ,MC_1.CUSTOMER_NM AS DEPOSIT_NM
	  ,MC_1.CUSTOMER_ID AS DEPOSIT_ID
	  ,MW_0.WAREHOUSE_ID
	  ,MW_0.WAREHOUSE_NM
	  ,LCT_0.LOCATION_ID AS CCL_LOCATION_ID
	  ,LCT_0.LOCATION_NM AS CCL_LOCATION_NM
	  ,LCT_0.WAREHOUSE_CD AS LCT_WAREHOUSE_CD
	  ,BM_0.MESSAGE_NM
	  ,MCC_0.DELIVERY_COURSE_CD_0
	  ,MCC_0.DELIVERY_COURSE_NM_0
-- [#2252]金額データ連携・納品書表示対応 2017.08.21 sampei Start
	  ,ESI_0.TOTAL_PRICE
	  ,ESI_0.TOTAL_TAX
	  ,ESI_0.UNIT_PRICE
	  ,ESI_0.PRICE
	  ,ESI_0.TAX
-- [#2252]金額データ連携・納品書表示対応 2017.08.21 sampei End
-- [#2253]予備項目対応 2017.08.18 sampei Start
	  ,ESI_0.SPARE_STR_1
	  ,ESI_0.SPARE_STR_2
	  ,ESI_0.SPARE_STR_3
	  ,ESI_0.SPARE_NUM_1
	  ,ESI_0.SPARE_NUM_2
	  ,ESI_0.SPARE_NUM_3
-- [#2253]予備項目対応 2017.08.18 sampei End

-- ELSE SELECT COUNT(*)
/*END*/
	FROM E_SHIPPING_INST ESI_0
		INNER JOIN M_CLIENT MC_0 ON MC_0.CLIENT_CD = ESI_0.CLIENT_CD
		INNER JOIN M_CENTER MCT_0 ON MCT_0.CENTER_CD = ESI_0.CENTER_CD
		-- [#246][2.1.0 バグ・品質向上対策] 入荷予定/出荷指示受信テーブルの物理名を(～ID)から(～CD)に修正 2016.11.22 honma Mod Start
		LEFT JOIN M_PROCESS_TYPE MPT ON MPT.PROCESS_TYPE_CD = ESI_0.PROCESS_TYPE_CD
		-- [#246][2.1.0 バグ・品質向上対策] 入荷予定/出荷指示受信テーブルの物理名を(～ID)から(～CD)に修正 2016.11.22 honma Mod End
			AND MPT.SHIPPING_FLG = '1'
			AND MPT.DEL_FLG = '0'
		LEFT JOIN M_WAREHOUSE MW_0 ON MW_0.CENTER_ID = MCT_0.CENTER_ID
			AND MW_0.WAREHOUSE_CD = ESI_0.WAREHOUSE_CD
			AND MW_0.DEL_FLG = '0'
		-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana Start
		LEFT JOIN V_DICT VD_0
			ON VD_0.DICT_ID = MPT.DICT_ID
			AND (VD_0.CULTURE_ID = /*pmb.cultureId*/11111111111 OR VD_0.CULTURE_ID IS NULL)
		-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana End
		LEFT JOIN M_STOCK_TYPE MST ON MST.STOCK_TYPE_CD = ESI_0.STOCK_TYPE_CD
			AND MST.DEL_FLG = '0'
		-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana Start
		LEFT JOIN V_DICT VD_1
			ON VD_1.DICT_ID = MST.DICT_ID
			AND (VD_1.CULTURE_ID = /*pmb.cultureId*/11111111111 OR VD_1.CULTURE_ID IS NULL)
		-- [#49] 辞書マスタを辞書ビューに変更 2016.10.24 kawana End
		LEFT JOIN M_CUSTOMER DFLOC_0 ON DFLOC_0.CLIENT_ID = MC_0.CLIENT_ID
			AND DFLOC_0.CUSTOMER_CD = ESI_0.SUPPLY_CUSTOMER_CD
			AND DFLOC_0.DELIVERY_FLG = '1'
			AND DFLOC_0.DEL_FLG = '0'
		LEFT JOIN M_CUSTOMER DFLOC_1 ON DFLOC_1.CLIENT_ID = MC_0.CLIENT_ID
			AND DFLOC_1.CUSTOMER_CD = ESI_0.DELIV_CUSTOMER_CD
			AND DFLOC_1.DELIVERY_FLG = '1'
			AND DFLOC_1.DEL_FLG = '0'
		LEFT JOIN M_CUSTOMER MC_1 ON ESI_0.DEPOSIT_CD = MC_1.CUSTOMER_CD
			AND MC_1.CLIENT_ID = MC_0.CLIENT_ID
			AND MC_1.DEPOSIT_FLG = '1'
			AND MC_1.DEL_FLG = '0'
		LEFT JOIN M_DELIVERY_COURSE MDC_0 ON MDC_0.CENTER_ID = MCT_0.CENTER_ID
			AND MDC_0.DELIVERY_COURSE_CD = ESI_0.DELIVERY_COURSE_CD
			AND MDC_0.DEL_FLG = '0'
		LEFT JOIN M_PRODUCT MP_0 ON MP_0.CLIENT_ID = MC_0.CLIENT_ID
			AND MP_0.PRODUCT_CD = ESI_0.PRODUCT_CD
			AND MP_0.DEL_FLG = '0'
		LEFT JOIN B_MESSAGE BM_0
			ON BM_0.MESSAGE_CD = ESI_0.ERROR_MESSAGE_CD
			/*IF pmb.cultureId != null*/
			AND BM_0.CULTURE_ID = /*pmb.cultureId*/1
			/*END*/
		LEFT JOIN
			(SELECT	DFLOC.CENTER_CUSTOMER_ID AS CENTER_CUSTOMER_ID
				   ,DFLOC.CENTER_ID AS CENTER_ID
				   ,DFLOC.CUSTOMER_ID AS CUSTOMER_ID
				   ,DFLOC.DELIVERY_COURSE_ID AS DELIVERY_COURSE_ID
				   ,DFLOC.DELIVERY_ORDER AS DELIVERY_ORDER
				   ,DFLOC.DELIVERY_READ_TIME AS DELIVERY_READ_TIME
				   ,DFLOC.DEL_FLG AS DEL_FLG
				   ,DFLOC.VERSION_NO AS VERSION_NO
				   ,DFLOC.CONTROL_NO AS CONTROL_NO
				   ,DFLOC.ADD_DT AS ADD_DT
				   ,DFLOC.ADD_USER AS ADD_USER
				   ,DFLOC.ADD_PROCESS AS ADD_PROCESS
				   ,DFLOC.UPD_DT AS UPD_DT
				   ,DFLOC.UPD_USER AS UPD_USER
				   ,DFLOC.UPD_PROCESS AS UPD_PROCESS
				   ,DFREL_0.DELIVERY_COURSE_ID AS DELIVERY_COURSE_ID_0
				   ,DFREL_0.CENTER_ID AS CENTER_ID_0
				   ,DFREL_0.DELIVERY_COURSE_CD AS DELIVERY_COURSE_CD_0
				   ,DFREL_0.DELIVERY_COURSE_NM AS DELIVERY_COURSE_NM_0
				   ,DFREL_0.CARRIER_ID AS CARRIER_ID_0
				   ,DFREL_0.PICKING_TIME AS PICKING_TIME_0
				   ,DFREL_0.STOWAGE_TIME AS STOWAGE_TIME_0
				   ,DFREL_0.SHIPPING_TIME AS SHIPPING_TIME_0
				   ,DFREL_0.CARRIER_SLIP_YMT_ID AS CARRIER_SLIP_YMT_ID_0
				   ,DFREL_0.CARRIER_SLIP_SGW_ID AS CARRIER_SLIP_SGW_ID_0
				   ,DFREL_0.CARRIER_SLIP_YUPK_ID AS CARRIER_SLIP_YUPK_ID_0
				   ,DFREL_0.DEL_FLG AS DEL_FLG_0
				   ,DFREL_0.VERSION_NO AS VERSION_NO_0
				   ,DFREL_0.CONTROL_NO AS CONTROL_NO_0
				   ,DFREL_0.ADD_DT AS ADD_DT_0
				   ,DFREL_0.ADD_USER AS ADD_USER_0
				   ,DFREL_0.ADD_PROCESS AS ADD_PROCESS_0
				   ,DFREL_0.UPD_DT AS UPD_DT_0
				   ,DFREL_0.UPD_USER AS UPD_USER_0
				   ,DFREL_0.UPD_PROCESS AS UPD_PROCESS_0
				   ,DFREL_1.CENTER_ID AS CENTER_ID_1
				   ,DFREL_1.CENTER_CD AS CENTER_CD_1
				   ,DFREL_1.CENTER_NM AS CENTER_NM_1
				   ,DFREL_1.CENTER_ABBR AS CENTER_ABBR_1
				   ,DFREL_1.CULTURE_ID AS CULTURE_ID_1
				   ,DFREL_1.DEL_FLG AS DEL_FLG_1
				   ,DFREL_1.VERSION_NO AS VERSION_NO_1
				   ,DFREL_1.CONTROL_NO AS CONTROL_NO_1
				   ,DFREL_1.ADD_DT AS ADD_DT_1
				   ,DFREL_1.ADD_USER AS ADD_USER_1
				   ,DFREL_1.ADD_PROCESS AS ADD_PROCESS_1
				   ,DFREL_1.UPD_DT AS UPD_DT_1
				   ,DFREL_1.UPD_USER AS UPD_USER_1
				   ,DFREL_1.UPD_PROCESS AS UPD_PROCESS_1
			FROM M_CENTER_CUSTOMER DFLOC
				INNER JOIN M_DELIVERY_COURSE DFREL_0
					ON DFLOC.DELIVERY_COURSE_ID = DFREL_0.DELIVERY_COURSE_ID
				INNER JOIN M_CENTER DFREL_1
					ON DFLOC.CENTER_ID = DFREL_1.CENTER_ID
			WHERE DFLOC.CENTER_ID = /*pmb.centerId*/444444444444444) MCC_0
				ON MCC_0.CUSTOMER_ID = DFLOC_0.CUSTOMER_ID
				AND MCC_0.CENTER_ID = MCT_0.CENTER_ID
		LEFT JOIN (
			SELECT DFREL_6_0.WAREHOUSE_CD
				  ,DFLOC.LOCATION_ID AS LOCATION_ID
				  ,DFLOC.CENTER_ID AS CENTER_ID
				  ,DFLOC.ZONE_ID AS ZONE_ID
				  ,DFLOC.LOCATION_CD AS LOCATION_CD
				  ,DFLOC.LOCATION_NM AS LOCATION_NM
				  ,DFLOC.PICKING_LOCATION_FLG AS PICKING_LOCATION_FLG
				  ,DFLOC.PICKING_ORDER AS PICKING_ORDER
				  ,DFLOC.LOCATION_TYPE AS LOCATION_TYPE
				  ,DFLOC.ALLOC_ORDER AS ALLOC_ORDER
				  ,DFLOC.ALLOC_NG_FLG AS ALLOC_NG_FLG
				  ,DFLOC.REPLENISH_PRODUCT_ID AS REPLENISH_PRODUCT_ID
				  ,DFLOC.REPLENISH_STOCK_TYPE_ID AS REPLENISH_STOCK_TYPE_ID
				  ,DFLOC.REPLENISH_DEPOSIT_ID AS REPLENISH_DEPOSIT_ID
				  ,DFLOC.REPLENISH_P_NUM AS REPLENISH_P_NUM
				  ,DFLOC.REPLENISH_P_PRODUCT_SHAPE_ID AS REPLENISH_P_PRODUCT_SHAPE_ID
				  ,DFLOC.MAX_STORE_NUM AS MAX_STORE_NUM
				  ,DFLOC.MAX_STORE_PRODUCT_SHAPE_ID AS MAX_STORE_PRODUCT_SHAPE_ID
				  ,DFLOC.DEL_FLG AS DEL_FLG
				  ,DFLOC.VERSION_NO AS VERSION_NO
				  ,DFLOC.CONTROL_NO AS CONTROL_NO
				  ,DFLOC.ADD_DT AS ADD_DT
				  ,DFLOC.ADD_USER AS ADD_USER
				  ,DFLOC.ADD_PROCESS AS ADD_PROCESS
				  ,DFLOC.UPD_DT AS UPD_DT
				  ,DFLOC.UPD_USER AS UPD_USER
				  ,DFLOC.UPD_PROCESS AS UPD_PROCESS
			FROM M_LOCATION DFLOC
				INNER JOIN M_ZONE DFREL_6
					ON DFLOC.ZONE_ID = DFREL_6.ZONE_ID
					AND DFREL_6.DEL_FLG = '0'
				INNER JOIN M_WAREHOUSE DFREL_6_0
					ON DFREL_6.WAREHOUSE_ID = DFREL_6_0.WAREHOUSE_ID
					AND DFREL_6_0.DEL_FLG = '0'
			WHERE DFLOC.CENTER_ID = /*pmb.centerId*/44444444444444
				AND DFLOC.DEL_FLG = '0'
			--ORDER BY DFLOC.LOCATION_CD ASC
		) LCT_0
				ON LCT_0.CENTER_ID = MCT_0.CENTER_ID
				AND LCT_0.LOCATION_CD = ESI_0.LOCATION_CD
	WHERE 1 = 1
		AND ESI_0.RECEIVE_CD = /*pmb.receiveCd*/'E12345678901'
		AND ESI_0.CENTER_CD = /*pmb.centerCd*/'TOKYO'
		AND ESI_0.CLIENT_CD = /*pmb.clientCd*/'MK001'
		/*IF pmb.errorFlg != null*/
		AND ESI_0.ERROR_FLG = /*pmb.errorFlg*/'0'
		/*END*/
		/*IF pmb.importFlg != null*/
		AND ESI_0.IMPORT_FLG = /*pmb.importFlg*/'0'
		/*END*/
/*IF pmb.isPaging()*/
	ORDER BY ESI_0.SHIPPING_INST_ID ASC
			,ESI_0.RECEIVE_CD ASC
			,ESI_0.RECEIVE_ROW_ID ASC
/*END*/