/*
 [df:title]
 ロケーションマスタ受信一覧を取得します。

 [df:description]
  SQL Description here.

*/
-- #df:entity#
-- ##Long PICKING_ORDER##
-- ##String CLIENT_CD##
-- ##String LocGroupNm##
-- ##String ALLOC_NG_FLG_NM##
-- ##String DEL_FLG_NM##
-- ##String LIN_OR_BLOCK##
-- ##String LOCKBN_NM##
-- ##String REPLENISHMENT_ROUNDEDUP__UNIT_NM##
-- ##String TOSPLMD_NM##
-- ##String PRESPLMD_NM##
-- !df:pmb extends Paging!
-- !!AutoDetect!!
-- !!Long centerId!!
-- !!Long clientId!!
/*IF pmb.isPaging()*/
SELECT	 MLC.LocGroup,
		NULL	AS	LocGroupNm,
 		MLC.LOCATION_CD,
 		MLC.ALLOC_NG_FLG,
 		NULL	AS	ALLOC_NG_FLG_NM,
 		MLC.DEL_FLG,
		NULL	AS	DEL_FLG_NM,
 		MLC.LOCATION_NM,
 		MLC.PICKING_ORDER,
 		MLC.PALLETECAPACITY,
 		MLC.MAX_STORE_NUM,
		MLC.LINBLK,
		NULL	AS	LIN_OR_BLOCK,
		MLC.LOCID,
		NULL	AS	LOCKBN_NM,
		PRD.PRODUCT_CD,
		PRD.PRODUCT_NM,
		PRD.BRCTG,
		MLC.SPLREVUN,
		NULL	AS	REPLENISHMENT_ROUNDEDUP__UNIT_NM,
		MLC.SPLREVCTQA,
		MLC.REPLENISH_P_NUM,
		MLC.BSSPLPT,
		MLC.TOSPLMD,
		NULL	AS	TOSPLMD_NM,
		MLC.PRESPLMD,
		NULL	AS	PRESPLMD_NM,
 		MFC.TRANSPORTPRIORITY,
-- 		NULL	AS	TRANSPORTPRIORITY,
		MLC.VIRTUALLOCFLG,
-- 		NULL 	AS 	LINORBLK,
-- 		MLI.LINCD,
		MLI.LINNM,
-- 		MBL.BLKCD,
		MBL.BLKNM,
		CEN.CENTER_CD,
		CEN.CENTER_NM,
		PRD.CLIENT_ID,
		CLI.CLIENT_CD,
		CLI.CLIENT_NM,
 		MLC.LOCATION_ID,
 		MLC.UPD_DT,
 		BUS.USER_NM,
		LEFT	(MLC.LOCATION_CD,3)	AS	ZONE,

-- 		MLC.ALLOC_ORDER,
		NULL	AS	ALLOC_ORDER,	--引当順序
-- 		MLC.LOCATION_TYPE,
		NULL	AS	LOCATION_TYPE,	--ロケーション種別
-- 		MLC.REPLENISH_PRODUCT_ID,
		NULL	AS	REPLENISH_PRODUCT_ID,	--補充商品ID
-- 		MLC.REPLENISH_STOCK_TYPE_ID,
		NULL	AS	REPLENISH_STOCK_TYPE_ID,	--補充在庫区分ID
-- 		MLC.REPLENISH_DEPOSIT_ID,
		NULL	AS	REPLENISH_DEPOSIT_ID,		--補充預託ID
-- 		MLC.REPLENISH_P_PRODUCT_SHAPE_ID,
		NULL	AS	REPLENISH_P_PRODUCT_SHAPE_ID,	--補充点商品荷姿ID
-- 		MLC.MAX_STORE_PRODUCT_SHAPE_ID,
		NULL	AS	MAX_STORE_PRODUCT_SHAPE_ID,		--最大格納数商品荷姿ID
-- 		MLC.VERSION_NO,
		NULL	AS	VERSION_NO,
-- 		MLC.CONTROL_NO,
		NULL	AS	CONTROL_NO,
-- 		MLC.ADD_PROCESS,
		NULL	AS	ADD_PROCESS
		
-- ELSE SELECT COUNT(*)
/*END*/

FROM	M_LOCATION	MLC--ロケーションマスタ
--LEFT	JOIN	M_LOCATION_SUB				MLS--ロケーションマスタサブ
--		ON		MLS.LOCATION_ID				=		MLC.LOCATION_ID
--		AND		MLS.DEL_FLG					=		'0'

LEFT	JOIN	M_CENTER					CEN--拠点マスタ
		ON		CEN.CENTER_ID				=		MLC.CENTER_ID
		AND		CEN.DEL_FLG					=		'0'

LEFT	JOIN	M_MFCOMPANY					MFC--組織マスタ
		ON		MFC.COMPANY_CD				=		SUBSTRING(CEN.CENTER_CD,0,4)
		AND		MFC.DEL_FLG					=		'0'

--SUBSTRING(拠点マスタ.拠点CD,0,4) = 組織マスタ.組織CD


LEFT	JOIN	M_PRODUCT					PRD--銘柄マスタ
		ON		PRD.PRODUCT_ID				=		MLC.REPLENISH_PRODUCT_ID
		AND		PRD.DEL_FLG					=		'0'

--LEFT	JOIN	M_PRODUCT_SUB				PRS--銘柄マスタサブ
--		ON		PRS.PRODUCT_ID				=	PRD.PRODUCT_ID
--		AND		PRS.DEL_FLG					=		'0'

-- TODO:★確認
LEFT	JOIN	M_CLIN						MLI--ラインマスタ
		ON		MLI.CENTER_ID				=		MLC.CENTER_ID
		AND		MLI.LINCD					=		MLC.LINBLK
		AND		MLI.DEL_FLG					=		'0'

LEFT	JOIN	M_CBLK						MBL--ブロックマスタ
		ON		MBL.CENTER_ID				=		MLC.CENTER_ID
		AND		MBL.BLKCD					=		MLC.LINBLK
		AND		MBL.DEL_FLG					=		'0'

LEFT	JOIN	M_CLIENT					CLI--荷主マスタ
		ON		CLI.CLIENT_ID				=		PRD.CLIENT_ID
		AND		CLI.DEL_FLG					=		'0'

-- TODO:★確認
LEFT	JOIN	B_USER						BUS		--ユーザマスタ
		ON		BUS.USER_CD					=		MLC.UPD_USER
		AND		BUS.DEL_FLG					=		'0'


WHERE
-- TODO:★確認
--		CLI.CLIENT_ID		=		1
		MLC.CENTER_ID		=		/*pmb.centerId*/1
/*IF pmb.locGroup != null*/
	AND		MLC.LocGroup			=			/*pmb.locGroup*/'01'
/*END*/
/*IF pmb.allcNgFlg != null*/
	AND		MLC.ALLOC_NG_FLG		=		/*pmb.allcNgFlg*/'0'
/*END*/
/*IF pmb.locationCd != null*/
	AND		MLC.LOCATION_CD		LIKE		/*pmb.locationCd*/'A%'
/*END*/
/*IF pmb.zone != null*/
	AND		MLC.LOCATION_CD		LIKE		/*pmb.zone*/'A%'
/*END*/
/*IF pmb.delFlg != null*/
	AND		MLC.DEL_FLG			=		/*pmb.delFlg*/'0'
/*END*/
/*IF pmb.isPaging()*/
ORDER	BY
-- TODO:★確認
		MFC.TRANSPORTPRIORITY		ASC,--出力順
		MLC.DEL_FLG					ASC,
		MLC.LOCATION_CD				ASC
/*END*/
