/*
[df:title]
棚卸ヘッダをリスト検索、ケース在庫調査情報、在庫調査補正情報を取得する。

[df:description]
  SQL Description here.

*/
-- #df:entity#
-- !df:pmb extends Paging!
-- !!AutoDetect!!
-- !!Long centerId!!
-- !!Long clientId!!

SELECT 
TIH.INVENTORY_H_ID,
TT.TRCASEINVENTORY_ID,
TT.VERSION_NO	AS		VERSION_NO_CASE,
TTC.TRINVCORRECT_ID,
TTC.PUTDMYCASECD,
TTC.PUTDMYCUTCASECD,
TTC.PUTDMYCASEDETAILNO,
TTC.PUTDMYDIRECTIONNO,
TTC.PUTDMYDIRECTIONORDERGNO,
TTC.VERSION_NO	AS		VERSION_NO_CORRECT
FROM			T_INVENTORY_H						TIH--棚卸ヘッダ

INNER	JOIN	T_INVENTORY_INST					TII--棚卸指示
		ON		TII.INVENTORY_H_ID			=		TIH.INVENTORY_H_ID
		AND		TII.INVENTORY_INST_KBN		=		'01'
		AND		TII.DEL_FLG					=		'0'

INNER	JOIN	T_INVENTORY_B						TIB--棚卸ボディ
		ON		TIB.INVENTORY_H_ID			=		TIH.INVENTORY_H_ID
		AND		TIB.DEL_FLG					=		'0'

INNER	JOIN	T_TRCASEINVENTORY					TT--ケース在庫調査情報
		ON		TT.INVENTORYKEY				=		TIH.INVENTORY_KEY
		AND		TT.INVENTORY_B_ID			=		TIB.INVENTORY_B_ID
		AND		TT.DEL_FLG					=		'0'

INNER	JOIN	T_TRINVCORRECT						TTC--在庫調査補正情報
		ON		TTC.CASEINVENTORYNO			=		TT.CASEINVENTORYNO
		AND		TTC.DEL_FLG					=		'0'

-- 検索条件
WHERE	TIH.CENTER_ID			=	/*pmb.centerId*/1
AND		TIH.CLIENT_ID			=	/*pmb.clientId*/1
AND		TIH.INVENTORY_DT		=	/*pmb.inventoryDt*/'20140805'
AND		TIH.DEL_FLG				=	'0'
