/*
 [df:title]
 在庫調査指示一覧件数

 [df:description]
  在庫調査指示一覧件数を取得します。

*/

-- #df:entity#
-- !df:pmb extends Paging!
-- !!AutoDetect!!

/*IF pmb.isPaging()*/
SELECT
       TVH.INVENTORY_H_ID
      ,TVH.INVENTORY_DT
      ,MPR.PRODUCT_CD
      ,MPR.PRODUCT_NM
 	  ,MPR.CGGDID
 	  ,TVB.FCFLG
 	  ,MPR.USERNUM4
 	  ,MPR.USERNUM3
  	  ,TVB.DIFFQTY_HENPIN
  	  ,TVB.DIFFQTY_TAXREFOND
   	  ,TVB.CHARGE_NUM
   	  ,TVB.SUFFERER_QTY
   	  ,TVB.MONTH_STATUSSU
   	  ,TVB.BLUK_RECIVED_QTY
   	  ,TVB.REFUNDITEM_QTY
  	  ,MPR.UNIT1
  	  ,MPR.UNIT2
      ,DICT.DICT_NM AS CGGDID_NM
      ,DICT2.DICT_NM AS FCFLG_NM
  FROM T_INVENTORY_H TVH-- 棚卸ヘッダ
     INNER JOIN T_INVENTORY_B TVB  -- 棚卸ボディ
       ON TVB.INVENTORY_H_ID = TVH.INVENTORY_H_ID
      AND TVB.DEL_FLG = '0'
    INNER JOIN T_INVENTORY_INST TVI  -- 棚卸指示
       ON TVI.INVENTORY_H_ID = TVH.INVENTORY_H_ID
      AND TVI.DEL_FLG = '0'
    INNER JOIN M_PRODUCT MPR  -- 銘柄マスタ
       ON MPR.PRODUCT_ID = TVB.PRODUCT_ID
      AND MPR.DEL_FLG = '0'
	INNER JOIN B_CLASS BCS
	   ON BCS.CLASS_CD='CGGDID'
      AND BCS.DEL_FLG = '0'
	INNER JOIN B_CLASS_DTL BCD
	   ON BCD.CLASS_ID = BCS.CLASS_ID
      AND BCD.CLASS_DTL_CD = MPR.CGGDID
      AND BCD.DEL_FLG = '0'
	INNER JOIN B_DICT DICT
	   ON DICT.DICT_ID = BCD.DICT_ID
      AND DICT.DEL_FLG = '0'
	INNER JOIN B_CLASS BCS2
	   ON BCS2.CLASS_CD='FCFLG'
      AND BCS2.DEL_FLG = '0'
	INNER JOIN B_CLASS_DTL BCD2
	   ON BCD2.CLASS_ID = BCS2.CLASS_ID
      AND BCD2.CLASS_DTL_CD = TVB.FCFLG
      AND BCD2.DEL_FLG = '0'
	INNER JOIN B_DICT DICT2
	   ON DICT2.DICT_ID = BCD2.DICT_ID
      AND DICT2.DEL_FLG = '0'
    WHERE 
           TVI.INVENTORY_INST_KBN = /*pmb.inventoryInstKbn*/'00'
      AND TVH.INVENTORY_KEY = /*pmb.inventoryKey*/11111111111
      AND TVH.DEL_FLG = '0'
/*END*/     
/*IF pmb.isPaging()*/
ORDER BY
 	   MPR.CGGDID ASC
 	  ,TVB.FCFLG ASC
 	  ,MPR.USERNUM4 ASC
 	  ,MPR.USERNUM3 ASC
      ,MPR.PRODUCT_CD ASC
/*END*/
      