/*
 [df:title]
 在庫調査結果確認件数

 [df:description]
 棚卸ボディをリスト検索、レコード数を取得する

*/

-- #df:entity#
-- !df:pmb extends Paging!
-- !!AutoDetect!!
/*IF pmb.isPaging()*/
SELECT  TIB.INVENTORY_B_ID AS INVENTORY_B_ID
		,TIB.VERSION_NO AS VERSION_NO
		,DICT.DICT_NM AS INVENTORY_INST_KBN
		,DICT1.DICT_NM AS LOCATION_GRP
		,DICT2.DICT_NM AS CGGDID
		,TIH.INVENTORY_KEY AS INSTRUCTION_KEY
		,TIH.INVENTORY_DT AS INVENTORY_DT
		,INST.ADD_DT AS ADD_DT
		,INST.LINE_BLOCK AS LINE_BLOCK
		,INST.DIRECTIONAL_PISTON AS DIRECTIONAL_PISTON
		,INST.SORTING_ORDER AS SORTING_ORDER
		,INST.SORTING_NUM_TIMES AS SORTING_NUM_TIMES
		,INST.LOCATION_CD AS LOCATION_CD
		,TIB.PRODUCT_CD AS PRODUCT_CD
		,PROD.JAN_CD AS JAN_CD
		,PROD.PRODUCT_NM AS PRODUCT_NM
		,TIB.FIRMTRANSPORT_CD AS FIRM_TRANSPORT_CD
		,'' AS UNIT_NUM_BREAKDOWN
		,TIB.CHARGE_NUM AS CHARGE_NUM
		,TIB.ALLOC_NUM AS ALLOC_NUM
		,TIB.MOVE_NUM AS MOVE_NUM
		,'' AS INVENTORY_BEFORE_BREAKDOWN
		,TIB.INVENTORY_NUM AS INVENTORY_NUM
		,TIB.INVENTORY_NUM AS INVENTORY_NUM_OLD
		,'' AS INVENTORY_ITEMS
		,'' AS DIFFERENCE_NUM
		,'' AS DIFFERENCE_ITEMS
		,LOT.NOSHIPPINGFLG AS NO_SHIPPING_FLG
		,FORMAT(TIB.UPD_DT, 'HH:mm') AS UPD_DT
		,CENT.CENTER_CD AS CENTER_CD
		,CENT.CENTER_NM AS CENTER_NM
		,PROD.P_QTY AS P_QTY
		,PROD.UNIT1 AS UNIT1
		,PROD.UNIT2 AS UNIT2
		,PROD.USERNUM4 AS USERNUM4
		,0 AS INVENTORY_PARCENT
		,TIB.INVENTORY_INPUT_FLG AS INVENTORY_INPUT_FLG

-- ELSE SELECT COUNT(*)
/*END*/
FROM
	T_INVENTORY_B AS TIB
INNER JOIN T_INVENTORY_H AS TIH
	ON TIH.INVENTORY_H_ID = TIB.INVENTORY_H_ID
	AND TIH.DEL_FLG = '0'
INNER JOIN T_INVENTORY_INST AS INST
	ON INST.INVENTORY_H_ID = TIB.INVENTORY_H_ID
	AND INST.DEL_FLG = '0'
INNER JOIN M_PRODUCT AS PROD
	ON PROD.PRODUCT_CD = TIB.PRODUCT_CD
	AND PROD.CLIENT_ID = TIH.CLIENT_ID
	AND PROD.DEL_FLG = '0'
INNER JOIN T_LOT AS LOT
	ON LOT.PRODUCT_ID = PROD.PRODUCT_ID
	AND LOT.DEL_FLG = '0'
INNER JOIN M_CENTER AS CENT
	ON CENT.CENTER_ID = TIH.CENTER_ID
	AND CENT.CENTER_ID = /*pmb.centerId*/11111111111
	AND CENT.DEL_FLG = '0'

INNER JOIN B_CLASS AS CLS
	ON CLS.CLASS_CD = 'INVENTORY_INST_KBN'
	AND CLS.DEL_FLG = '0'
INNER JOIN B_CLASS_DTL AS CLSDTL
	ON CLSDTL.CLASS_DTL_CD = INST.INVENTORY_INST_KBN
	AND CLSDTL.CLASS_ID = CLS.CLASS_ID
	AND CLSDTL.DEL_FLG = '0'
INNER JOIN B_DICT AS DICT
	ON DICT.DICT_ID = CLSDTL.DICT_ID
	AND DICT.DEL_FLG = '0'

INNER JOIN B_CLASS AS CLS1
	ON CLS1.CLASS_CD = 'LOC_GROUP'
	AND CLS1.DEL_FLG = '0'
INNER JOIN B_CLASS_DTL AS CLSDTL1
	ON CLSDTL1.CLASS_DTL_CD = INST.LOCATION_GRP
	AND CLSDTL1.CLASS_ID = CLS1.CLASS_ID
	AND CLSDTL1.DEL_FLG = '0'
INNER JOIN B_DICT AS DICT1
	ON DICT1.DICT_ID = CLSDTL1.DICT_ID
	AND DICT1.DEL_FLG = '0'

INNER JOIN B_CLASS AS CLS2
	ON CLS2.CLASS_CD = 'CGGDID'
	AND CLS2.DEL_FLG = '0'
INNER JOIN B_CLASS_DTL AS CLSDTL2
	ON CLSDTL2.CLASS_DTL_CD = PROD.CGGDID
	AND CLSDTL2.CLASS_ID = CLS2.CLASS_ID
	AND CLSDTL2.DEL_FLG = '0'
INNER JOIN B_DICT AS DICT2
	ON DICT2.DICT_ID = CLSDTL2.DICT_ID
	AND DICT2.DEL_FLG = '0'
INNER JOIN M_LOCATION AS LOC
	ON LOC.LOCATION_ID = TIB.LOCATION_ID
	AND LOC.DEL_FLG = '0'

WHERE
	TIB.DEL_FLG = '0'
AND TIH.CLIENT_ID = /*pmb.clientId*/11111111111
AND TIH.CENTER_ID = /*pmb.centerId*/11111111111
/*IF pmb.inventoryInstKbn != null*/
AND INST.INVENTORY_INST_KBN = /*pmb.inventoryInstKbn*/'11111111111'
/*END*/
/*IF pmb.inventoryInstAddDt != null*/
AND FORMAT(INST.ADD_DT, 'yyyyMMdd') = /*pmb.inventoryInstAddDt*/'11111111111'
/*END*/
/*IF pmb.locationGrp != null*/
AND INST.LOCATION_GRP = /*pmb.locationGrp*/'11111111111'
/*END*/
/*IF pmb.productCd != null*/
AND PROD.PRODUCT_CD LIKE /*pmb.productCd*/'11111111111%'
/*END*/
/*IF pmb.capProduct != null*/
AND PROD.USERNUM4 = /*pmb.capProduct*/11111111111
/*END*/
/*IF pmb.cggdid != null*/
AND PROD.CGGDID = /*pmb.cggdid*/'11111111111'
/*END*/
/*IF pmb.inventoryInstKey != null*/
AND TIH.INVENTORY_KEY = /*pmb.inventoryInstKey*/11111111111
/*END*/
/*IF pmb.stockTakingInput != null*/
AND TIB.INVENTORY_INPUT_FLG = /*pmb.stockTakingInput*/'11111111111'
/*END*/
/*IF pmb.unmatch == '1'*/
AND TIB.CHARGE_NUM <> TIB.INVENTORY_NUM
/*END*/
/*IF pmb.fromLocationCd != null*/
AND LOC.LOCATION_CD >= /*pmb.fromLocationCd*/'11111111111'
/*END*/
/*IF pmb.toLocationCd != null*/
AND LOC.LOCATION_CD <= /*pmb.toLocationCd*/'11111111111'
/*END*/

/*IF pmb.isPaging()*/
ORDER BY
	TIH.INVENTORY_KEY ASC
	,INST.LOCATION_CD ASC
	,TIB.FCFLG ASC
	,PROD.USERNUM3 ASC
	,TIB.FIRMTRANSPORT_CD ASC
/*END*/








