/*
 [df:title]
 在庫調査指示一覧件数

 [df:description]
  在庫調査指示一覧件数を取得します。

*/

-- #df:entity#
-- !df:pmb extends Paging!
-- !!AutoDetect!!

/*IF pmb.isPaging()*/
SELECT
       TVI.INVENTORY_INST_KBN
      ,TVH.INVENTORY_KEY
      ,TVH.INVENTORY_DT
      ,TVI.PRODUCT_DIVISION
      ,TVI.LINE_BLOCK
      ,TVI.DIRECTIONAL_PISTON
      ,TVI.LOCATION_GRP
      ,TVI.LOCATION_CD
      ,TVI.FROM_LOCATION_CD
      ,TVI.TO_LOCATION_CD
      ,MPR.PRODUCT_CD
      ,MPR.PRODUCT_NM
      ,DICT.DICT_NM AS INVENTORY_INST_KBN_NM
      ,DICT2.DICT_NM AS PRODUCT_DIVISION_NM
      ,DICT3.DICT_NM AS LOCATION_GRP_NM
      ,MC.CLIENT_CD
      ,MC.CLIENT_NM
      ,MCT.CENTER_CD
      ,MCT.CENTER_NM      
-- ELSE SELECT COUNT(*)
/*END*/      
  FROM T_INVENTORY_INST TVI-- 棚卸指示
    INNER JOIN T_INVENTORY_H TVH -- 棚卸ヘッダ
       ON TVH.INVENTORY_H_ID = TVI.INVENTORY_H_ID
      AND TVH.DEL_FLG = '0'
     LEFT OUTER JOIN M_PRODUCT MPR  -- 銘柄マスタ
       ON MPR.CLIENT_ID = TVH.CLIENT_ID
      AND MPR.PRODUCT_CD = TVI.PRODUCT_CD
      AND MPR.DEL_FLG = '0'
	INNER JOIN B_CLASS BCS
	   ON BCS.CLASS_CD='INVENTORY_INST_KBN'
      AND BCS.DEL_FLG = '0'
	INNER JOIN B_CLASS_DTL BCD
	   ON BCD.CLASS_ID = BCS.CLASS_ID
      AND BCD.CLASS_DTL_CD = TVI.INVENTORY_INST_KBN
      AND BCD.DEL_FLG = '0'
	INNER JOIN B_DICT DICT
	   ON DICT.DICT_ID = BCD.DICT_ID
      AND DICT.DEL_FLG = '0'
	LEFT OUTER JOIN B_CLASS BCS2
	   ON BCS2.CLASS_CD='SYHN_KBN'
      AND BCS2.DEL_FLG = '0'
	LEFT OUTER JOIN B_CLASS_DTL BCD2
	   ON BCD2.CLASS_ID = BCS2.CLASS_ID
      AND BCD2.CLASS_DTL_CD = TVI.PRODUCT_DIVISION
      AND BCD2.DEL_FLG = '0'
	LEFT OUTER JOIN B_DICT DICT2
	   ON DICT2.DICT_ID = BCD2.DICT_ID
      AND DICT2.DEL_FLG = '0'
	LEFT OUTER JOIN B_CLASS BCS3
	   ON BCS3.CLASS_CD='LOC_GROUP'
      AND BCS3.DEL_FLG = '0'
	LEFT OUTER JOIN B_CLASS_DTL BCD3
	   ON BCD3.CLASS_ID = BCS3.CLASS_ID
      AND BCD3.CLASS_DTL_CD = TVI.LOCATION_GRP
      AND BCD3.DEL_FLG = '0'
	LEFT OUTER JOIN B_DICT DICT3
	   ON DICT3.DICT_ID = BCD3.DICT_ID
      AND DICT3.DEL_FLG = '0'
	INNER JOIN M_CLIENT MC
	   ON MC.CLIENT_ID = TVH.CLIENT_ID
      AND MC.DEL_FLG = '0'	
   　INNER JOIN M_CENTER MCT
	   ON MCT.CENTER_ID = TVH.CENTER_ID
      AND MCT.DEL_FLG = '0'
    WHERE 
          TVH.CENTER_ID = /*pmb.centerId*/11111111111
      AND TVH.CLIENT_ID = /*pmb.clientId*/11111111111
      AND TVI.INVENTORY_INST_KBN = /*pmb.inventoryInstKbn*/'00'
      /*IF pmb.inventoryKey != null*/
      AND TVH.INVENTORY_KEY LIKE /*pmb.inventoryKey*/'1%'
      /*END*/
      /*IF pmb.inventoryDt != null*/
      AND TVH.INVENTORY_DT = /*pmb.inventoryDt*/'20140430'
      /*END*/
      /*IF pmb.locationGrp != null*/
      AND TVI.LOCATION_GRP = /*pmb.locationGrp*/'00'
      /*END*/
      AND TVI.DEL_FLG = '0'
/*IF pmb.isPaging()*/
ORDER BY
  TVH.INVENTORY_KEY DESC
/*END*/
      