/*
 [df:title]
  Packing Slipを取得します。出庫ヘッダ1レコード毎です。

 [df:description]
  SQL Description here.
*/

-- #df:entity#

-- !df:pmb extends Paging!
-- !!AutoDetect!!

/*IF pmb.isPaging()*/
SELECT
	MAIN.CLIENT_CD,
	MAX(MAIN.CLIENT_NM) AS CLIENT_NM,
	MAX(MAIN.CLIENT_ADDRESS1) AS CLIENT_ADDRESS1,
	MAX(MAIN.CLIENT_ADDRESS2) AS CLIENT_ADDRESS2,
	MAX(MAIN.CLIENT_ADDRESS3) AS CLIENT_ADDRESS3,
	MAX(MAIN.CLIENT_TEL_NO) AS CLIENT_TEL_NO,
	MAIN.SHIPPING_DT AS SHIPPING_DT,
	MAIN.CLIENT_SHIPPING_NO AS CLIENT_SHIPPING_NO,
	MAX(MAIN.SUPPLY_CUSTOMER_NM) AS SUPPLY_CUSTOMER_NM,
	MAX(MAIN.BILL_ADDRESS1) AS BILL_ADDRESS1,
	MAX(MAIN.BILL_ADDRESS2) AS BILL_ADDRESS2,
	MAX(MAIN.BILL_ADDRESS3) AS BILL_ADDRESS3,
	MAX(MAIN.BILL_TEL_NO) AS BILL_TEL_NO,
	MAX(MAIN.DELIV_CUSTOMER_NM) AS DELIV_CUSTOMER_NM,
	MAX(MAIN.DELIV_ADDRESS1) AS DELIV_ADDRESS1,
	MAX(MAIN.DELIV_ADDRESS2) AS DELIV_ADDRESS2,
	MAX(MAIN.DELIV_ADDRESS3) AS DELIV_ADDRESS3,
	MAX(MAIN.DELIV_TEL_NO) AS DELIV_TEL_NO,
	MAIN.PRODUCT_CD AS PRODUCT_CD,
	MAX(MAIN.PRODUCT_NM) AS PRODUCT_NM,
	SUM(MAIN.ALLOC_NUM) AS ALLOC_NUM
FROM(
	SELECT
		MC.CLIENT_CD,
		MC.CLIENT_NM AS CLIENT_NM,
		MCRMCC.ADDRESS1 AS CLIENT_ADDRESS1,
		MCRMCC.ADDRESS2 AS CLIENT_ADDRESS2,
		MCRMCC.ADDRESS3 AS CLIENT_ADDRESS3,
		MCRMCC.TEL_NO AS CLIENT_TEL_NO,
		TAIH.SHIPPING_DT AS SHIPPING_DT,
		TSIH.CLIENT_SHIPPING_NO AS CLIENT_SHIPPING_NO,
		TAIH.SUPPLY_CUSTOMER_NM AS SUPPLY_CUSTOMER_NM,
		MCR.ADDRESS1 AS BILL_ADDRESS1,
		MCR.ADDRESS2 AS BILL_ADDRESS2,
		MCR.ADDRESS3 AS BILL_ADDRESS3,
		MCR.TEL_NO AS BILL_TEL_NO,
		TAIH.DELIV_CUSTOMER_NM AS DELIV_CUSTOMER_NM,
		TAIH.DELIV_ADDRESS1 AS DELIV_ADDRESS1,
		TAIH.DELIV_ADDRESS2 AS DELIV_ADDRESS2,
		TAIH.DELIV_ADDRESS3 AS DELIV_ADDRESS3,
		TAIH.DELIV_TEL_NO AS DELIV_TEL_NO,
		MP.PRODUCT_CD AS PRODUCT_CD,
		MP.PRODUCT_NM AS PRODUCT_NM,
		TPB.PICKING_NUM AS ALLOC_NUM
	  FROM T_PICKING_H TPH -- 出庫ヘッダ
	     INNER JOIN T_PICKING_B TPB -- 出庫ボディ
	            ON TPH.PICKING_H_ID = TPB.PICKING_H_ID
	     LEFT JOIN M_CLIENT MC -- 荷主マスタ
	            ON TPH.CLIENT_ID = MC.CLIENT_ID
	           AND MC.DEL_FLG = '0'
	     LEFT JOIN M_CENTER MR -- センタマスタ
	            ON TPH.CENTER_ID = MR.CENTER_ID
	           AND MR.DEL_FLG = '0'
	     LEFT JOIN T_ALLOC_INST_H TAIH -- 引当指示ヘッダ
	            ON TPH.ALLOC_INST_H_ID = TAIH.ALLOC_INST_H_ID
	           AND TAIH.DEL_FLG = '0'
	     LEFT JOIN T_PICKING_R TPR -- 出庫帳票
	            ON TPH.PICKING_H_ID = TPR.PICKING_H_ID
	           AND TPR.DEL_FLG = '0'
	     LEFT JOIN M_CUSTOMER MCR -- 取引先マスタ
	            ON TAIH.SUPPLY_CUSTOMER_ID = MCR.CUSTOMER_ID
	           AND MCR.DEL_FLG = '0'
	     LEFT JOIN M_CLIENT_CENTER MCC -- 荷主センタマスタ
	            ON MC.CLIENT_ID = MCC.CLIENT_ID
	           AND MR.CENTER_ID = MCC.CENTER_ID
	           AND MCC.DEL_FLG = '0'
	     LEFT JOIN M_CUSTOMER MCRMCC -- 取引先マスタ
	            ON MCC.CUSTOMER_ID = MCRMCC.CUSTOMER_ID
	           AND MCRMCC.DEL_FLG = '0'
		 LEFT JOIN  T_SHIPPING_INST_H TSIH -- 出荷指示ヘッダ
		        ON TAIH.ALLOC_INST_H_ID = TSIH.ALLOC_INST_H_ID
		       AND TSIH.DEL_FLG = '0'
		       /*IF pmb.clientShippingNo != null*/
		       AND TSIH.CLIENT_SHIPPING_NO = /*pmb.clientShippingNo*/'11111111111'
	           /*END*/
		 LEFT JOIN T_STOCK TS -- 在庫
		        ON TPB.STOCK_ID = TS.STOCK_ID
		       AND TS.DEL_FLG = '0'
		 LEFT JOIN M_PRODUCT MP
	            ON TS.PRODUCT_ID = MP.PRODUCT_ID
	           AND MP.DEL_FLG = '0'

	 WHERE TPH.DEL_FLG = '0'
	   AND TPB.DEL_FLG = '0'
	   /*IF pmb.controlNo != null*/
	   AND TPR.CONTROL_NO = /*pmb.controlNo*/11111111111
	   /*END*/
--	 ORDER BY
--	          MC.CLIENT_CD ASC
--	         ,TAIH.SHIPPING_DT ASC
--	         ,TSIH.CLIENT_SHIPPING_NO ASC
--	         ,MP.PRODUCT_CD ASC
	   ) MAIN
 GROUP BY
          MAIN.CLIENT_CD
         ,MAIN.SHIPPING_DT
         ,MAIN.CLIENT_SHIPPING_NO
         ,MAIN.PRODUCT_CD
/*END*/
/*IF pmb.isPaging()*/
 ORDER BY
          CLIENT_CD ASC
         ,SHIPPING_DT ASC
         ,CLIENT_SHIPPING_NO ASC
         ,PRODUCT_CD ASC
         ,ALLOC_NUM ASC
/*END*/
