/*
 [df:title]
 印刷用不適品ラベル一覧。

 [df:description]
  印刷用の不適品ラベル一覧を出力します。

*/

-- #df:entity#

-- !df:pmb extends Paging!
-- !!AutoDetect!!

SELECT
  TRBAD.TRBADITEMCASE_ID,
  TRBAD.TARGETMON,
  TRBAD.BADITEMCD,
  TRBAD.ITEMCD,
  TRBAD.CREATEDDATE,
  TRBAD.INOUTKBN,
  TRBAD.VA_EXTDATA2,
  MCE.CENTER_CD,
  MCE.CENTER_NM,
  MPR.PRODUCT_ABBR,
  (MPR.UNIT1 * MPR.UNIT2) AS CASE_NUM,
  MPR.ALLOCPOLICYKEY,
  MPR.USERNUM3
FROM T_TRBADITEMCASE TRBAD -- 不適品ラベル情報
INNER JOIN M_CENTER MCE -- 拠点マスタ
  ON MCE.CENTER_ID = TRBAD.CENTER_ID
  AND MCE.DEL_FLG = '0'
INNER JOIN M_CLIENT MCL -- 荷主マスタ
  ON MCL.CLIENT_ID = TRBAD.CLIENT_ID
  AND MCL.DEL_FLG = '0'
INNER JOIN M_PRODUCT MPR  -- 銘柄マスタ
  ON MPR.CLIENT_ID = TRBAD.CLIENT_ID
  AND MPR.PRODUCT_CD = TRBAD.ITEMCD
  AND MPR.DEL_FLG = '0'
WHERE
  TRBAD.CONTROL_NO = /*pmb.controlNo*/11111111111
  AND TRBAD.DEL_FLG = '0'
ORDER BY
  TRBAD.TARGETMON ASC,
  TRBAD.VA_EXTDATA2 ASC,
  MPR.USERNUM3 ASC,
  TRBAD.ITEMCD ASC,
  TRBAD.BADITEMCD ASC
