/*
 [df:title]
  販売物流在庫情報をリスト検索

 [df:description]
  販売物流在庫情報をリスト検索
*/

-- #df:entity#

-- !df:pmb!
-- !!Long centerId!!
-- !!Long clientId!!
-- !!String centerCd!!
-- !!String systemDt!!
-- !!String srymd!!
-- !!AutoDetect!!
SELECT
ISNULL(PRODUCT.LOTATRB1TITLE, INV.PRODUCT_CD) PCD,
PRODUCT.USERNUM4 USERNUM4, --CAP銘柄区分
(
    CASE WHEN PRODUCT.USERNUM4 != 0
    THEN  0
    ELSE
        SUM(
            (ISNULL(SUB3.SLQACB, 0) + ISNULL(SUB4.SLQACB, 0)
                - ISNULL(SUB5.SLQACB, 0) - ISNULL(SUB6.SLQACB, 0)) * PRODUCT.UNIT1 * PRODUCT.UNIT2
            +
            (ISNULL(SUB3.SLQACT, 0) + ISNULL(SUB4.SLQACT, 0)
                - ISNULL(SUB5.SLQACT, 0) - ISNULL(SUB6.SLQACT, 0)) * PRODUCT.UNIT2
            +
            (ISNULL(SUB3.SLQANUM, 0) + ISNULL(SUB4.SLQANUM, 0)
                - ISNULL(SUB5.SLQANUM, 0) - ISNULL(SUB6.SLQANUM, 0))
            )
    END
) TOTAL
FROM T_TRHANBAIINV INV
INNER JOIN M_PRODUCT PRODUCT
ON PRODUCT.CLIENT_ID = INV.CLIENT_ID
AND PRODUCT.PRODUCT_CD = INV.PRODUCT_CD
AND PRODUCT.DEL_FLG = '0'
LEFT JOIN
(SELECT
    TASR.ZZMATNR PCD,          -- 銘柄CD
    SUM(TASR.SLQACB) SLQACB,   -- 販売数量、ダンボール数
    SUM(TASR.SLQACT) SLQACT,   -- 販売数量、カートン数
    SUM(TASR.SLQANUM) SLQANUM  -- 販売数量、個数
FROM T_CORDDTASR TASR -- さしずデータ(仕分中)
INNER JOIN T_CORDHDR HEAD -- さしずヘッダ
ON  HEAD.ORDER_H_ID = TASR.ORDER_H_ID
AND HEAD.CLIENT_ID  = /*pmb.clientId*/1
AND HEAD.CENTER_ID  = /*pmb.centerId*/1
AND HEAD.DEL_FLG    = '0'
INNER JOIN M_CENTER CENTER
ON CENTER.CENTER_CD = TASR.DPCD
AND CENTER.DEL_FLG  = '0'
INNER JOIN M_MFCOMPANY COMPANY
ON COMPANY.COMPANY_CD = CENTER.CENTER_CD
AND TASR.DLVYMD BETWEEN COMPANY.F_USER3 AND COMPANY.F_USER4
AND (COMPANY.F_USER2 IS NULL OR COMPANY.F_USER2 > TASR.DLVYMD)
AND (
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '00' AND '19'
        OR
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '40' AND '99'
    )
AND COMPANY.DEL_FLG  = '0'
WHERE TASR.SRWHCD = /*pmb.centerCd*/'1'
AND   TASR.SRYMD  = /*pmb.srymd*/'20221111' -- 仕分作業日付
AND (
    TASR.HDVID = 0
    OR TASR.HDVID BETWEEN '2' AND '9'
    )
AND TASR.BOXNO = ''
AND TASR.SROPRTCNT > 0
AND TASR.SLPTYP NOT IN ('ZO71','ZO72','ZO73','ZO74','ZO75','ZO76')
AND TASR.DEL_FLG = '0'
GROUP BY TASR.ZZMATNR) SUB3
ON INV.PRODUCT_CD = SUB3.PCD
LEFT JOIN
(SELECT
    TAEC.ZZMATNR PCD,           -- 銘柄CD
    SUM(TAEC.SLQACB)  SLQACB,   -- 販売数量、ダンボール数
    SUM(TAEC.SLQACT)  SLQACT,   -- 販売数量、カートン数
    SUM(TAEC.SLQANUM) SLQANUM   -- 販売数量、個数
FROM T_CORDDTAEC TAEC -- さしずデータ(取替用)
INNER JOIN T_CORDHDR HEAD -- さしずヘッダ
ON  HEAD.ORDER_H_ID = TAEC.ORDER_H_ID
AND HEAD.CLIENT_ID  = /*pmb.clientId*/1
AND HEAD.CENTER_ID  = /*pmb.centerId*/1
AND HEAD.DEL_FLG    = '0'
INNER JOIN M_CENTER CENTER
ON CENTER.CENTER_CD = TAEC.DPCD
AND CENTER.DEL_FLG  = '0'
INNER JOIN M_MFCOMPANY COMPANY
ON COMPANY.COMPANY_CD = CENTER.CENTER_CD
AND TAEC.DLVYMD BETWEEN COMPANY.F_USER3 AND COMPANY.F_USER4
AND (COMPANY.F_USER2 IS NULL OR COMPANY.F_USER2 > TAEC.DLVYMD)
AND (
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '00' AND '19'
        OR
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '40' AND '99'
    )
AND COMPANY.DEL_FLG  = '0'
WHERE TAEC.SRWHCD = /*pmb.centerCd*/'1'
AND   TAEC.SRYMD  = /*pmb.srymd*/'20221111' -- 仕分作業日付
AND (
    TAEC.HDVID = 0
    OR TAEC.HDVID BETWEEN '2' AND '9'
    )
AND TAEC.BOXNO = ''
AND TAEC.SROPRTCNT > 0
AND TAEC.DEL_FLG = '0'
GROUP BY TAEC.ZZMATNR) SUB4
ON INV.PRODUCT_CD = SUB4.PCD
LEFT JOIN
(SELECT
    TASR.ZZMATNR PCD,          -- 銘柄CD
    SUM(TASR.SLQACB) SLQACB,   -- 販売数量、ダンボール数
    SUM(TASR.SLQACT) SLQACT,   -- 販売数量、カートン数
    SUM(TASR.SLQANUM) SLQANUM  -- 販売数量、個数
FROM T_CORDDTASR TASR -- さしずデータ(仕分中)
INNER JOIN T_CORDHDR HEAD -- さしずヘッダ
ON  HEAD.ORDER_H_ID = TASR.ORDER_H_ID
AND HEAD.CLIENT_ID  = /*pmb.clientId*/1
AND HEAD.CENTER_ID  = /*pmb.centerId*/1
AND HEAD.DEL_FLG    = '0'
INNER JOIN M_CENTER CENTER
ON CENTER.CENTER_CD = TASR.DPCD
AND CENTER.DEL_FLG  = '0'
INNER JOIN M_MFCOMPANY COMPANY
ON COMPANY.COMPANY_CD = CENTER.CENTER_CD
AND TASR.DLVYMD BETWEEN COMPANY.F_USER3 AND COMPANY.F_USER4
AND (COMPANY.F_USER2 IS NULL OR COMPANY.F_USER2 > TASR.DLVYMD)
AND (
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '00' AND '19'
        OR
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '40' AND '99'
    )
AND COMPANY.DEL_FLG  = '0'
WHERE TASR.SRWHCD = /*pmb.centerCd*/'1'
AND   TASR.SRYMD  = /*pmb.srymd*/'20221111' -- 仕分作業日付
AND (
    TASR.HDVID = 0
    OR TASR.HDVID BETWEEN '2' AND '9'
    )
AND TASR.BOXNO = ''
AND TASR.SROPRTCNT > 0
AND TASR.DLVYMD <= SRYMD
AND TASR.SLPTYP NOT IN ('ZO71','ZO72','ZO73','ZO74','ZO75','ZO76')
AND TASR.DEL_FLG = '0'
GROUP BY TASR.ZZMATNR) SUB5
ON INV.PRODUCT_CD = SUB5.PCD
LEFT JOIN
(SELECT
    TAEC.ZZMATNR PCD,          -- 銘柄CD
    SUM(TAEC.SLQACB) SLQACB,   -- 販売数量、ダンボール数
    SUM(TAEC.SLQACT) SLQACT,   -- 販売数量、カートン数
    SUM(TAEC.SLQANUM) SLQANUM  -- 販売数量、個数
FROM T_CORDDTAEC TAEC -- さしずデータ(取替用)
INNER JOIN T_CORDHDR HEAD -- さしずヘッダ
ON  HEAD.ORDER_H_ID = TAEC.ORDER_H_ID
AND HEAD.CLIENT_ID  = /*pmb.clientId*/1
AND HEAD.CENTER_ID  = /*pmb.centerId*/1
AND HEAD.DEL_FLG    = '0'
INNER JOIN M_CENTER CENTER
ON CENTER.CENTER_CD = TAEC.DPCD
AND CENTER.DEL_FLG  = '0'
INNER JOIN M_MFCOMPANY COMPANY
ON COMPANY.COMPANY_CD = CENTER.CENTER_CD
AND TAEC.DLVYMD BETWEEN COMPANY.F_USER3 AND COMPANY.F_USER4
AND (COMPANY.F_USER2 IS NULL OR COMPANY.F_USER2 > TAEC.DLVYMD)
AND (
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '00' AND '19'
        OR
        COMPANY.WAREHOUSE_FUNC_KBN BETWEEN '40' AND '99'
    )
AND COMPANY.DEL_FLG  = '0'
WHERE TAEC.SRWHCD = /*pmb.centerCd*/'1'
AND   TAEC.SRYMD  = /*pmb.srymd*/'20221111' -- 仕分作業日付
AND (
    TAEC.HDVID = 0
    OR TAEC.HDVID BETWEEN '2' AND '9'
    )
AND TAEC.BOXNO = ''
AND TAEC.SROPRTCNT > 0
AND TAEC.DLVYMD <= TAEC.SRYMD
AND TAEC.DEL_FLG = '0'
GROUP BY TAEC.ZZMATNR) SUB6
ON INV.PRODUCT_CD = SUB6.PCD
WHERE INV.CENTER_ID = /*pmb.centerId*/1
AND   INV.CLIENT_ID = /*pmb.clientId*/1
AND   CONVERT(VARCHAR(8), INV.STOCKDATETIME, 112) = /*pmb.systemDt*/20241111
AND   INV.GOODITEMKBN = '0'  -- (適品)
AND   INV.DEL_FLG = '0'
GROUP BY ISNULL(PRODUCT.LOTATRB1TITLE, INV.PRODUCT_CD), PRODUCT.USERNUM4