/*
 [df:title]
  販売物流在庫情報をリスト検索

 [df:description]
  販売物流在庫情報をリスト検索
*/

-- #df:entity#

-- !df:pmb!
-- !!Long centerId!!
-- !!Long clientId!!
-- !!String centerCd!!
-- !!String systemDt!!
-- !!String srymd!!
-- !!AutoDetect!!
SELECT
ISNULL(PRODUCT.LOTATRB1TITLE, INV.PRODUCT_CD) PCD,
SUM(
    SUB.SLQACB * PRODUCT.UNIT1 * PRODUCT.UNIT2
    + SUB.SLQACT * PRODUCT.UNIT2
    ) TOTAL
FROM  T_TRHANBAIINV INV
INNER JOIN M_PRODUCT PRODUCT
ON    PRODUCT.CLIENT_ID  = INV.CLIENT_ID
AND   PRODUCT.PRODUCT_CD = INV.PRODUCT_CD
AND   PRODUCT.DEL_FLG    = '0'
INNER JOIN
(SELECT
    TASR.ZZMATNR PCD,                -- 銘柄CD
    ISNULL(TASR.SLQACB, 0) SLQACB,   -- 販売数量、ダンボール数
    ISNULL(TASR.SLQACT, 0) SLQACT    -- 販売数量、カートン数
FROM  T_CORDDTASR TASR -- さしずデータ(仕分中)
INNER JOIN T_CORDHDR HEAD -- さしずヘッダ
ON    HEAD.ORDER_H_ID = TASR.ORDER_H_ID
AND   HEAD.CLIENT_ID  = /*pmb.clientId*/1
AND   HEAD.CENTER_ID  = /*pmb.centerId*/1
AND   HEAD.DEL_FLG    = '0'
INNER JOIN M_PRODUCT PRODUCT
ON    PRODUCT.CLIENT_ID  = HEAD.CLIENT_ID
AND   PRODUCT.PRODUCT_CD = TASR.ZZMATNR
AND   TASR.DLVYMD BETWEEN PRODUCT.USERDATE1 AND PRODUCT.USERDATE2
AND (
      PRODUCT.USERDATE3 IS NULL
      OR PRODUCT.USERDATE3 > TASR.DLVYMD
    )
AND   PRODUCT.DEL_FLG = '0'
INNER JOIN M_CDRCATT CATT
ON    CATT.CENTER_ID    = /*pmb.centerId*/1
AND   CATT.CLIENT_ID    = /*pmb.clientId*/1
AND   CATT.DRCCD        = TASR.DED
AND   CATT.ZZPSTNID     = TASR.PSTNID
AND   CATT.REMOTEISLAND = '1' -- (離島)
AND   CATT.DEL_FLG      = '0'
WHERE TASR.SRWHCD  = /*pmb.centerCd*/'1'
AND   TASR.SRYMD   = /*pmb.srymd*/'20221111' -- 仕分作業日付
AND   TASR.ORDDVFG = '1'
AND   TASR.SRLINCD NOT IN ('X1', 'X2')
AND   TASR.DEL_FLG = '0') SUB
ON    SUB.PCD = INV.PRODUCT_CD
WHERE INV.CENTER_ID = /*pmb.centerId*/1
AND   INV.CLIENT_ID = /*pmb.clientId*/1
AND   CONVERT(VARCHAR(8), INV.STOCKDATETIME, 112) = /*pmb.systemDt*/20241111
AND   INV.GOODITEMKBN = '0'  -- (適品)
AND   INV.DEL_FLG = '0'
GROUP BY ISNULL(PRODUCT.LOTATRB1TITLE, INV.PRODUCT_CD)