/*
[df:title]
重複する融通指示データを検索する。

[df:description]
  SQL Description here.

*/
-- #df:entity#
-- !df:pmb!
-- !!AutoDetect!!
-- !!Long centerId!!
-- !!Long clientId!!
WITH SQL2 AS
(
	SELECT WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,WRII.RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
		,SUM(CAST(WRII.QTY AS INT)) AS QTY_SUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO != /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,WRII.RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
	ORDER BY WRII.FLEXLNS_NO
		,WRII.ITEM_CD
	Offset 0 ROWS
)

SELECT COUNT(*) AS COUNT_NUM
FROM
( 
	SELECT WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,WRII.RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
		,SUM(CAST(WRII.QTY AS INT)) AS QTY_SUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
	ORDER BY WRII.FLEXLNS_NO
		,WRII.ITEM_CD
	Offset 0 ROWS
) AS SQL1
INNER JOIN SQL2
ON  SQL2.SCH_DATE = SQL1.SCH_DATE
AND SQL2.SUPPLIER_CD = SQL1.SUPPLIER_CD
AND SQL2.RCV_DATE = SQL1.RCV_DATE
AND SQL2.SHIP_CD = SQL1.SHIP_CD
AND SQL2.ITEM_CD = SQL1.ITEM_CD
AND SQL2.QTY_SUM = SQL1.QTY_SUM
AND (
	SELECT COUNT(DISTINCT WRII.ITEM_CD) AS ITEM_CD_NUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = SQL2.FLEXLNS_NO
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
	) 
= 
(
	SELECT COUNT(DISTINCT WRII.ITEM_CD) AS ITEM_CD_NUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
)

WHERE
(
	SELECT COUNT(FLEXLNS_NO) FROM SQL2
)
= 
(
	SELECT COUNT(DISTINCT WRII.ITEM_CD) AS ITEM_CD_NUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
)


GROUP BY SQL2.FLEXLNS_NO












