/*
[df:title]
融通指示一括取込ワークを基に融通輸送情報、融通輸送明細情報を検索する。

[df:description]
  SQL Description here.

*/
-- #df:entity#
-- !df:pmb!
-- !!AutoDetect!!
-- !!Long centerId!!
-- !!Long clientId!!
WITH SQL2 AS 
(
	SELECT SQL3.FLEXIBITYNO
		,SQL3.TRANSPORTCD
		,SQL3.SUPPLIERCD
		,SQL3.SCHDATE
		,SQL3.SHIPCD
		,SQL3.RCVDATE
		,SQL3.PRODUCT_CD
		,SUM(SQL3.NUM) AS NUM
	FROM 
	(
		SELECT TTRF.FLEXIBITYNO
			,TTRF.TRANSPORTCD
			,TTRF.SUPPLIERCD
			,TTRF.SCHDATE
			,TTRF.SHIPCD
			,TTRF.RCVDATE
			,MP.PRODUCT_CD
			,(TTRFD.QTYCASE * MP.UNIT1 * MP.UNIT2) + 
			(TTRFD.QTYBOWL * MP.UNIT2) AS NUM
		FROM T_TRFLEXIBILITY TTRF
		INNER JOIN T_TRFLEXIBILITYDETAIL TTRFD
			ON TTRFD.FLEXIBLE_TRANSPORT_INFO_ID = TTRF.FLEXIBLE_TRANSPORT_INFO_ID
			AND TTRFD.DEL_FLG = '0'
		INNER JOIN M_PRODUCT MP
			ON MP.CLIENT_ID = /*pmb.clientId*/1111111111
			AND MP.PRODUCT_ID = TTRFD.PRODUCT_ID
			AND MP.DEL_FLG = '0'
		WHERE TTRF.DEL_FLG = '0'
	) AS SQL3
	GROUP BY SQL3.FLEXIBITYNO
		,SQL3.TRANSPORTCD
		,SQL3.SUPPLIERCD
		,SQL3.SCHDATE
		,SQL3.SHIPCD
		,SQL3.RCVDATE
		,SQL3.PRODUCT_CD
		,SQL3.FLEXIBITYNO
 	ORDER BY SQL3.TRANSPORTCD
 		,SQL3.PRODUCT_CD
	Offset 0 ROWS
)

SELECT SQL2.FLEXIBITYNO
	,SQL2.TRANSPORTCD
FROM
(
	SELECT WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,WRII.RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
		,SUM(CAST(WRII.QTY AS INT)) AS QTY_SUM
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
		,WRII.SCH_DATE
		,WRII.SUPPLIER_CD
		,WRII.RCV_DATE
		,WRII.SHIP_CD
		,WRII.ITEM_CD
 	ORDER BY WRII.FLEXLNS_NO
 		,WRII.ITEM_CD
	Offset 0 ROWS
) AS SQL1 
INNER JOIN SQL2
ON SQL2.SCHDATE = SQL1.SCH_DATE
AND SQL2.SUPPLIERCD = SQL1.SUPPLIER_CD
AND SQL2.RCVDATE = SQL1.RCV_DATE
AND SQL2.SHIPCD = SQL1.SHIP_CD
AND SQL2.PRODUCT_CD = SQL1.ITEM_CD
AND SQL2.NUM = SQL1.QTY_SUM
AND 
(
	SELECT COUNT(DISTINCT TTRFD.PRODUCT_ID) AS PRODUCT_ID_COUNT
	FROM T_TRFLEXIBILITYDETAIL TTRFD
	INNER JOIN T_TRFLEXIBILITY TTRF
		ON TTRF.FLEXIBLE_TRANSPORT_INFO_ID = TTRFD.FLEXIBLE_TRANSPORT_INFO_ID
		AND TTRF.DEL_FLG = '0'
	WHERE TTRF.FLEXIBITYNO = SQL2.FLEXIBITYNO
		AND TTRFD.DEL_FLG = '0'
	GROUP BY TTRF.FLEXIBITYNO
)
=
(
	SELECT COUNT(DISTINCT WRII.ITEM_CD) AS ITEM_CD_COUNT
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
)

WHERE
(
	SELECT COUNT(FLEXIBITYNO) FROM SQL2
)
=
(
	SELECT COUNT(DISTINCT WRII.ITEM_CD) AS ITEM_CD_COUNT
	FROM W_REPLENISH_INST_INPUT WRII
	WHERE WRII.RECEIVE_CD = /*pmb.receiveCd*/'000000001'
		AND WRII.CENTER_CD = /*pmb.centerCd*/'11111'
		AND WRII.CLIENT_CD = /*pmb.clientCd*/'11111'
		AND WRII.FLEXLNS_NO = /*pmb.flexlnsNo*/'11111'
		AND WRII.DEL_FLG = '0'
	GROUP BY WRII.FLEXLNS_NO
)

GROUP BY SQL2.FLEXIBITYNO
		,SQL2.TRANSPORTCD




















