INSERT 	
INTO B_CLASS_DTL_SUB( 	
  CLASS_DTL_ID	
  , OTHER1_COMMENT
  , OTHER2_COMMENT	
) 	
SELECT	
  BCD.CLASS_DTL_ID	
  , 'コードに対応する拠点コード'	
  , 'コードに対応する拠点グループ'	
FROM	
  B_CLASS BC 	
  INNER JOIN B_CLASS_DTL BCD 	
    ON BC.CLASS_ID = BCD.CLASS_ID 	
WHERE	
  1 = 1 	
  AND BC.CLASS_CD = 'STORAGEWAREHOUSECD' 	
  AND BCD.CLASS_DTL_CD = 'JP45';	


INSERT 	
INTO B_CLASS_DTL_SUB( 	
  CLASS_DTL_ID	
  , OTHER1_COMMENT
  , OTHER2_COMMENT	
) 	
SELECT	
  BCD.CLASS_DTL_ID	
  , 'コードに対応する拠点コード'	
  , 'コードに対応する拠点グループ'	
FROM	
  B_CLASS BC 	
  INNER JOIN B_CLASS_DTL BCD 	
    ON BC.CLASS_ID = BCD.CLASS_ID 	
WHERE	
  1 = 1 	
  AND BC.CLASS_CD = 'STORAGEWAREHOUSECD' 	
  AND BCD.CLASS_DTL_CD = 'JP46';	
