//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:15:55 AM JST
//

package com.oneslogi.wms.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"errorShippingNumberDetail"
})
@XmlRootElement(name = "errorShippingNumberList")
public class ErrorShippingNumberList {

	protected List<ErrorShippingNumberDetail> errorShippingNumberDetail;

	public List<ErrorShippingNumberDetail> getErrorShippingNumberDetail() {
		if (errorShippingNumberDetail == null) {
			errorShippingNumberDetail = new ArrayList<ErrorShippingNumberDetail>();
		}
		return this.errorShippingNumberDetail;
	}

	public void addErrorShippingNumberDetail(ErrorShippingNumberDetail pdd) {
		if (errorShippingNumberDetail == null) {
			errorShippingNumberDetail = new ArrayList<ErrorShippingNumberDetail>();
		}
		errorShippingNumberDetail.add(pdd);
	}

}
