//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:09:51 AM JST
//

package com.oneslogi.wms.xml;

import java.math.BigInteger;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"itemDetail",
		"itemTotalPrice",
		"totalKosu"
})
@XmlRootElement(name = "itemList")
public class ItemList {

	@XmlElement(required = true)
	protected List<ItemDetail> itemDetail;
	@XmlElement(required = true)
	protected BigInteger itemTotalPrice;
	@XmlElement(required = true)
	protected BigInteger totalKosu;

	public List<ItemDetail> getItemDetail() {
		return itemDetail;
	}

	public void setItemDetail(List<ItemDetail> itemDetail) {
		this.itemDetail = itemDetail;
	}

	public BigInteger getItemTotalPrice() {
		return itemTotalPrice;
	}

	public void setItemTotalPrice(BigInteger itemTotalPrice) {
		this.itemTotalPrice = itemTotalPrice;
	}

	public BigInteger getTotalKosu() {
		return totalKosu;
	}

	public void setTotalKosu(BigInteger totalKosu) {
		this.totalKosu = totalKosu;
	}

}
