//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:09:51 AM JST
//

package com.oneslogi.wms.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"title",
		"orderId",
		"gift",
		"noshi",
		"shopTel",
		"shopFax",
		"shopYubin",
		"shopAdd1",
		"shopAdd2",
		"shopAdd3",
		"shopNm1",
		"shopNm2",
		"shopMailAddress",
		"teikei1",
		"teikei2",
		"teikei3",
		"teikei4",
		"teikei5",
		"teikei6",
		"teikei7",
		"teikei8",
		"teikei9",
		"biko",
		"orderDate",
		"shopNm",
		"paymentNm",
		"itemTotalTax",
		"soryo",
		"tesuryo",
		"couponPrice",
		"usedPoint",
		"totalPrice",
		"itemList",
		"freeEntry1",
		"freeEntry2",
		"freeEntry3",
		"freeEntry4",
		"freeEntry5",
		"freeEntry6",
		"freeEntry7",
		"freeEntry8",
		"freeEntry9",
		"freeEntry10",
		"freeEntry11",
		"freeEntry12",
		"freeEntry13",
		"freeEntry14",
		"freeEntry15",
		"freeEntry16",
		"freeEntry17",
		"freeEntry18",
		"freeEntry19",
		"freeEntry20"
})
@XmlRootElement(name = "nouhinshoData")
public class NouhinshoData {

	protected String title;

	protected Integer orderId;

	protected String gift;

	protected String noshi;

	protected String shopTel;

	protected String shopFax;

	protected Integer shopYubin;

	protected String shopAdd1;

	protected String shopAdd2;

	protected String shopAdd3;

	protected String shopNm1;

	protected String shopNm2;

	protected String shopMailAddress;

	protected String teikei1;

	protected String teikei2;

	protected String teikei3;

	protected String teikei4;

	protected String teikei5;

	protected String teikei6;

	protected String teikei7;

	protected String teikei8;

	protected String teikei9;

	protected String biko;

	protected String orderDate;

	protected String shopNm;

	protected String paymentNm;

	protected Integer itemTotalTax;

	protected Integer soryo;

	protected Integer tesuryo;

	protected Integer couponPrice;

	protected Integer usedPoint;

	protected Integer totalPrice;

	protected ItemList itemList;

	protected String freeEntry1;

	protected String freeEntry2;

	protected String freeEntry3;

	protected String freeEntry4;

	protected String freeEntry5;

	protected String freeEntry6;

	protected String freeEntry7;

	protected String freeEntry8;

	protected String freeEntry9;

	protected String freeEntry10;

	protected String freeEntry11;

	protected String freeEntry12;

	protected String freeEntry13;

	protected String freeEntry14;

	protected String freeEntry15;

	protected String freeEntry16;

	protected String freeEntry17;

	protected String freeEntry18;

	protected String freeEntry19;

	protected String freeEntry20;

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public String getGift() {
		return gift;
	}

	public void setGift(String gift) {
		this.gift = gift;
	}

	public String getNoshi() {
		return noshi;
	}

	public void setNoshi(String noshi) {
		this.noshi = noshi;
	}

	public String getShopTel() {
		return shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	public String getShopFax() {
		return shopFax;
	}

	public void setShopFax(String shopFax) {
		this.shopFax = shopFax;
	}

	public Integer getShopYubin() {
		return shopYubin;
	}

	public void setShopYubin(Integer shopYubin) {
		this.shopYubin = shopYubin;
	}

	public String getShopAdd1() {
		return shopAdd1;
	}

	public void setShopAdd1(String shopAdd1) {
		this.shopAdd1 = shopAdd1;
	}

	public String getShopAdd2() {
		return shopAdd2;
	}

	public void setShopAdd2(String shopAdd2) {
		this.shopAdd2 = shopAdd2;
	}

	public String getShopAdd3() {
		return shopAdd3;
	}

	public void setShopAdd3(String shopAdd3) {
		this.shopAdd3 = shopAdd3;
	}

	public String getShopNm1() {
		return shopNm1;
	}

	public void setShopNm1(String shopNm1) {
		this.shopNm1 = shopNm1;
	}

	public String getShopNm2() {
		return shopNm2;
	}

	public void setShopNm2(String shopNm2) {
		this.shopNm2 = shopNm2;
	}

	public String getShopMailAddress() {
		return shopMailAddress;
	}

	public void setShopMailAddress(String shopMailAddress) {
		this.shopMailAddress = shopMailAddress;
	}

	public String getTeikei1() {
		return teikei1;
	}

	public void setTeikei1(String teikei1) {
		this.teikei1 = teikei1;
	}

	public String getTeikei2() {
		return teikei2;
	}

	public void setTeikei2(String teikei2) {
		this.teikei2 = teikei2;
	}

	public String getTeikei3() {
		return teikei3;
	}

	public void setTeikei3(String teikei3) {
		this.teikei3 = teikei3;
	}

	public String getTeikei4() {
		return teikei4;
	}

	public void setTeikei4(String teikei4) {
		this.teikei4 = teikei4;
	}

	public String getTeikei5() {
		return teikei5;
	}

	public void setTeikei5(String teikei5) {
		this.teikei5 = teikei5;
	}

	public String getTeikei6() {
		return teikei6;
	}

	public void setTeikei6(String teikei6) {
		this.teikei6 = teikei6;
	}

	public String getTeikei7() {
		return teikei7;
	}

	public void setTeikei7(String teikei7) {
		this.teikei7 = teikei7;
	}

	public String getTeikei8() {
		return teikei8;
	}

	public void setTeikei8(String teikei8) {
		this.teikei8 = teikei8;
	}

	public String getTeikei9() {
		return teikei9;
	}

	public void setTeikei9(String teikei9) {
		this.teikei9 = teikei9;
	}

	public String getBiko() {
		return biko;
	}

	public void setBiko(String biko) {
		this.biko = biko;
	}

	public String getOrderDate() {
		return orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	public String getShopNm() {
		return shopNm;
	}

	public void setShopNm(String shopNm) {
		this.shopNm = shopNm;
	}

	public String getPaymentNm() {
		return paymentNm;
	}

	public void setPaymentNm(String paymentNm) {
		this.paymentNm = paymentNm;
	}

	public Integer getItemTotalTax() {
		return itemTotalTax;
	}

	public void setItemTotalTax(Integer itemTotalTax) {
		this.itemTotalTax = itemTotalTax;
	}

	public Integer getSoryo() {
		return soryo;
	}

	public void setSoryo(Integer soryo) {
		this.soryo = soryo;
	}

	public Integer getTesuryo() {
		return tesuryo;
	}

	public void setTesuryo(Integer tesuryo) {
		this.tesuryo = tesuryo;
	}

	public Integer getCouponPrice() {
		return couponPrice;
	}

	public void setCouponPrice(Integer couponPrice) {
		this.couponPrice = couponPrice;
	}

	public Integer getUsedPoint() {
		return usedPoint;
	}

	public void setUsedPoint(Integer usedPoint) {
		this.usedPoint = usedPoint;
	}

	public Integer getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	public ItemList getItemList() {
		return itemList;
	}

	public void setItemList(ItemList itemList) {
		this.itemList = itemList;
	}

	public String getFreeEntry1() {
		return freeEntry1;
	}

	public void setFreeEntry1(String freeEntry1) {
		this.freeEntry1 = freeEntry1;
	}

	public String getFreeEntry2() {
		return freeEntry2;
	}

	public void setFreeEntry2(String freeEntry2) {
		this.freeEntry2 = freeEntry2;
	}

	public String getFreeEntry3() {
		return freeEntry3;
	}

	public void setFreeEntry3(String freeEntry3) {
		this.freeEntry3 = freeEntry3;
	}

	public String getFreeEntry4() {
		return freeEntry4;
	}

	public void setFreeEntry4(String freeEntry4) {
		this.freeEntry4 = freeEntry4;
	}

	public String getFreeEntry5() {
		return freeEntry5;
	}

	public void setFreeEntry5(String freeEntry5) {
		this.freeEntry5 = freeEntry5;
	}

	public String getFreeEntry6() {
		return freeEntry6;
	}

	public void setFreeEntry6(String freeEntry6) {
		this.freeEntry6 = freeEntry6;
	}

	public String getFreeEntry7() {
		return freeEntry7;
	}

	public void setFreeEntry7(String freeEntry7) {
		this.freeEntry7 = freeEntry7;
	}

	public String getFreeEntry8() {
		return freeEntry8;
	}

	public void setFreeEntry8(String freeEntry8) {
		this.freeEntry8 = freeEntry8;
	}

	public String getFreeEntry9() {
		return freeEntry9;
	}

	public void setFreeEntry9(String freeEntry9) {
		this.freeEntry9 = freeEntry9;
	}

	public String getFreeEntry10() {
		return freeEntry10;
	}

	public void setFreeEntry10(String freeEntry10) {
		this.freeEntry10 = freeEntry10;
	}

	public String getFreeEntry11() {
		return freeEntry11;
	}

	public void setFreeEntry11(String freeEntry11) {
		this.freeEntry11 = freeEntry11;
	}

	public String getFreeEntry12() {
		return freeEntry12;
	}

	public void setFreeEntry12(String freeEntry12) {
		this.freeEntry12 = freeEntry12;
	}

	public String getFreeEntry13() {
		return freeEntry13;
	}

	public void setFreeEntry13(String freeEntry13) {
		this.freeEntry13 = freeEntry13;
	}

	public String getFreeEntry14() {
		return freeEntry14;
	}

	public void setFreeEntry14(String freeEntry14) {
		this.freeEntry14 = freeEntry14;
	}

	public String getFreeEntry15() {
		return freeEntry15;
	}

	public void setFreeEntry15(String freeEntry15) {
		this.freeEntry15 = freeEntry15;
	}

	public String getFreeEntry16() {
		return freeEntry16;
	}

	public void setFreeEntry16(String freeEntry16) {
		this.freeEntry16 = freeEntry16;
	}

	public String getFreeEntry17() {
		return freeEntry17;
	}

	public void setFreeEntry17(String freeEntry17) {
		this.freeEntry17 = freeEntry17;
	}

	public String getFreeEntry18() {
		return freeEntry18;
	}

	public void setFreeEntry18(String freeEntry18) {
		this.freeEntry18 = freeEntry18;
	}

	public String getFreeEntry19() {
		return freeEntry19;
	}

	public void setFreeEntry19(String freeEntry19) {
		this.freeEntry19 = freeEntry19;
	}

	public String getFreeEntry20() {
		return freeEntry20;
	}

	public void setFreeEntry20(String freeEntry20) {
		this.freeEntry20 = freeEntry20;
	}
}
