//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:53:38 AM JST
//

package com.oneslogi.wms.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"printRequestId",
		"createDate",
		"resultCode",
		"url",
		"haisoKosu",
		"userManageNumber",
		"kokyakuCode",
		"otodokeAdd1",
		"otodokeAdd2",
		"otodokeAdd3",
		"otodokeNm1",
		"otodokeNm2",
		"otodokeYubin",
		"otodokeTel",
		"otodokeMailAddress",
		"iraiPrintFlg",
		"iraiAdd1",
		"iraiAdd2",
		"iraiAdd3",
		"iraiNm1",
		"iraiNm2",
		"iraiYubin",
		"iraiTel",
		"iraiMailAddress",
		"shippingDate",
		"kiji1",
		"kiji2",
		"kiji3",
		"kiji4",
		"kiji5",
		"kiji6",
		"binsyuCode",
		"daibikiFlg",
		"daibikiType",
		"shiteiDate",
		"shiteiTimeCode",
		"daibikiKingaku",
		"daibikiTax",
		"weight1",
		"weight2",
		"careSeal1",
		"careSeal2",
		"careSeal3",
		"hokenKingaku",
		"eidomeFlg",
		"depotCode",
		"mark",
		"nouhinshoData",
		"resultCodeList",
		"depotInfo",
		"shippingNumberList"
})
@XmlRootElement(name = "printDataDetail")
public class PrintDataDetail {

	protected String printRequestId;

	protected String createDate;

	protected String resultCode;

	protected String url;

	protected Integer haisoKosu;

	protected String userManageNumber;

	protected String kokyakuCode;

	protected String otodokeAdd1;

	protected String otodokeAdd2;

	protected String otodokeAdd3;

	protected String otodokeNm1;

	protected String otodokeNm2;

	protected String otodokeYubin;

	protected String otodokeTel;

	protected String otodokeMailAddress;

	protected Integer iraiPrintFlg;

	protected String iraiAdd1;

	protected String iraiAdd2;

	protected String iraiAdd3;

	protected String iraiNm1;

	protected String iraiNm2;

	protected String iraiYubin;

	protected String iraiTel;

	protected String iraiMailAddress;

	protected String shippingDate;

	protected String kiji1;

	protected String kiji2;

	protected String kiji3;

	protected String kiji4;

	protected String kiji5;

	protected String kiji6;

	protected String binsyuCode;

	protected String daibikiFlg;

	protected String daibikiType;

	protected String shiteiDate;

	protected String shiteiTimeCode;

	protected String daibikiKingaku;

	protected String daibikiTax;

	protected String weight1;

	protected String weight2;

	protected String careSeal1;

	protected String careSeal2;

	protected String careSeal3;

	protected String hokenKingaku;

	protected String eidomeFlg;

	protected String depotCode;

	protected String mark;

	protected NouhinshoData nouhinshoData;

	protected ResultCodeList resultCodeList;

	protected DepotInfo depotInfo;

	protected ShippingNumberList shippingNumberList;

	public String getPrintRequestId() {
		return printRequestId;
	}

	public void setPrintRequestId(String printRequestId) {
		this.printRequestId = printRequestId;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getResultCode() {
		return resultCode;
	}

	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getHaisoKosu() {
		return haisoKosu;
	}

	public void setHaisoKosu(Integer haisoKosu) {
		this.haisoKosu = haisoKosu;
	}

	public String getUserManageNumber() {
		return userManageNumber;
	}

	public void setUserManageNumber(String userManageNumber) {
		this.userManageNumber = userManageNumber;
	}

	public String getKokyakuCode() {
		return kokyakuCode;
	}

	public void setKokyakuCode(String kokyakuCode) {
		this.kokyakuCode = kokyakuCode;
	}

	public String getOtodokeAdd1() {
		return otodokeAdd1;
	}

	public void setOtodokeAdd1(String otodokeAdd1) {
		this.otodokeAdd1 = otodokeAdd1;
	}

	public String getOtodokeAdd2() {
		return otodokeAdd2;
	}

	public void setOtodokeAdd2(String otodokeAdd2) {
		this.otodokeAdd2 = otodokeAdd2;
	}

	public String getOtodokeAdd3() {
		return otodokeAdd3;
	}

	public void setOtodokeAdd3(String otodokeAdd3) {
		this.otodokeAdd3 = otodokeAdd3;
	}

	public String getOtodokeNm1() {
		return otodokeNm1;
	}

	public void setOtodokeNm1(String otodokeNm1) {
		this.otodokeNm1 = otodokeNm1;
	}

	public String getOtodokeNm2() {
		return otodokeNm2;
	}

	public void setOtodokeNm2(String otodokeNm2) {
		this.otodokeNm2 = otodokeNm2;
	}

	public String getOtodokeYubin() {
		return otodokeYubin;
	}

	public void setOtodokeYubin(String otodokeYubin) {
		this.otodokeYubin = otodokeYubin;
	}

	public String getOtodokeTel() {
		return otodokeTel;
	}

	public void setOtodokeTel(String otodokeTel) {
		this.otodokeTel = otodokeTel;
	}

	public String getOtodokeMailAddress() {
		return otodokeMailAddress;
	}

	public void setOtodokeMailAddress(String otodokeMailAddress) {
		this.otodokeMailAddress = otodokeMailAddress;
	}

	public Integer getIraiPrintFlg() {
		return iraiPrintFlg;
	}

	public void setIraiPrintFlg(Integer iraiPrintFlg) {
		this.iraiPrintFlg = iraiPrintFlg;
	}

	public String getIraiAdd1() {
		return iraiAdd1;
	}

	public void setIraiAdd1(String iraiAdd1) {
		this.iraiAdd1 = iraiAdd1;
	}

	public String getIraiAdd2() {
		return iraiAdd2;
	}

	public void setIraiAdd2(String iraiAdd2) {
		this.iraiAdd2 = iraiAdd2;
	}

	public String getIraiAdd3() {
		return iraiAdd3;
	}

	public void setIraiAdd3(String iraiAdd3) {
		this.iraiAdd3 = iraiAdd3;
	}

	public String getIraiNm1() {
		return iraiNm1;
	}

	public void setIraiNm1(String iraiNm1) {
		this.iraiNm1 = iraiNm1;
	}

	public String getIraiNm2() {
		return iraiNm2;
	}

	public void setIraiNm2(String iraiNm2) {
		this.iraiNm2 = iraiNm2;
	}

	public String getIraiYubin() {
		return iraiYubin;
	}

	public void setIraiYubin(String iraiYubin) {
		this.iraiYubin = iraiYubin;
	}

	public String getIraiTel() {
		return iraiTel;
	}

	public void setIraiTel(String iraiTel) {
		this.iraiTel = iraiTel;
	}

	public String getIraiMailAddress() {
		return iraiMailAddress;
	}

	public void setIraiMailAddress(String iraiMailAddress) {
		this.iraiMailAddress = iraiMailAddress;
	}

	public String getShippingDate() {
		return shippingDate;
	}

	public void setShippingDate(String shippingDate) {
		this.shippingDate = shippingDate;
	}

	public String getKiji1() {
		return kiji1;
	}

	public void setKiji1(String kiji1) {
		this.kiji1 = kiji1;
	}

	public String getKiji2() {
		return kiji2;
	}

	public void setKiji2(String kiji2) {
		this.kiji2 = kiji2;
	}

	public String getKiji3() {
		return kiji3;
	}

	public void setKiji3(String kiji3) {
		this.kiji3 = kiji3;
	}

	public String getKiji4() {
		return kiji4;
	}

	public void setKiji4(String kiji4) {
		this.kiji4 = kiji4;
	}

	public String getKiji5() {
		return kiji5;
	}

	public void setKiji5(String kiji5) {
		this.kiji5 = kiji5;
	}

	public String getKiji6() {
		return kiji6;
	}

	public void setKiji6(String kiji6) {
		this.kiji6 = kiji6;
	}

	public String getBinsyuCode() {
		return binsyuCode;
	}

	public void setBinsyuCode(String binsyuCode) {
		this.binsyuCode = binsyuCode;
	}

	public String getDaibikiFlg() {
		return daibikiFlg;
	}

	public void setDaibikiFlg(String daibikiFlg) {
		this.daibikiFlg = daibikiFlg;
	}

	public String getDaibikiType() {
		return daibikiType;
	}

	public void setDaibikiType(String daibikiType) {
		this.daibikiType = daibikiType;
	}

	public String getShiteiDate() {
		return shiteiDate;
	}

	public void setShiteiDate(String shiteiDate) {
		this.shiteiDate = shiteiDate;
	}

	public String getShiteiTimeCode() {
		return shiteiTimeCode;
	}

	public void setShiteiTimeCode(String shiteiTimeCode) {
		this.shiteiTimeCode = shiteiTimeCode;
	}

	public String getDaibikiKingaku() {
		return daibikiKingaku;
	}

	public void setDaibikiKingaku(String daibikiKingaku) {
		this.daibikiKingaku = daibikiKingaku;
	}

	public String getDaibikiTax() {
		return daibikiTax;
	}

	public void setDaibikiTax(String daibikiTax) {
		this.daibikiTax = daibikiTax;
	}

	public String getWeight1() {
		return weight1;
	}

	public void setWeight1(String weight1) {
		this.weight1 = weight1;
	}

	public String getWeight2() {
		return weight2;
	}

	public void setWeight2(String weight2) {
		this.weight2 = weight2;
	}

	public String getCareSeal1() {
		return careSeal1;
	}

	public void setCareSeal1(String careSeal1) {
		this.careSeal1 = careSeal1;
	}

	public String getCareSeal2() {
		return careSeal2;
	}

	public void setCareSeal2(String careSeal2) {
		this.careSeal2 = careSeal2;
	}

	public String getCareSeal3() {
		return careSeal3;
	}

	public void setCareSeal3(String careSeal3) {
		this.careSeal3 = careSeal3;
	}

	public String getHokenKingaku() {
		return hokenKingaku;
	}

	public void setHokenKingaku(String hokenKingaku) {
		this.hokenKingaku = hokenKingaku;
	}

	public String getEidomeFlg() {
		return eidomeFlg;
	}

	public void setEidomeFlg(String eidomeFlg) {
		this.eidomeFlg = eidomeFlg;
	}

	public String getDepotCode() {
		return depotCode;
	}

	public void setDepotCode(String depotCode) {
		this.depotCode = depotCode;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	public NouhinshoData getNouhinshoData() {
		return nouhinshoData;
	}

	public void setNouhinshoData(NouhinshoData nouhinshoData) {
		this.nouhinshoData = nouhinshoData;
	}

	public ResultCodeList getResultCodeList() {
		return resultCodeList;
	}

	public void setResultCodeList(ResultCodeList resultCodeList) {
		this.resultCodeList = resultCodeList;
	}

	public DepotInfo getDepotInfo() {
		return depotInfo;
	}

	public void setDepotInfo(DepotInfo depotInfo) {
		this.depotInfo = depotInfo;
	}

	public ShippingNumberList getShippingNumberList() {
		return shippingNumberList;
	}

	public void setShippingNumberList(ShippingNumberList shippingNumberList) {
		this.shippingNumberList = shippingNumberList;
	}

}
