//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:15:55 AM JST
//

package com.oneslogi.wms.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"shippingNumber"
})
@XmlRootElement(name = "shippingNumberList")
public class ShippingNumberList {

	protected List<String> shippingNumber;

	public List<String> getShippingNumber() {
		if (shippingNumber == null) {
			shippingNumber = new ArrayList<String>();
		}
		return this.shippingNumber;
	}

	public void addShippingNumber(String shippingNumber) {
		if (this.shippingNumber == null) {
			this.shippingNumber = new ArrayList<String>();
		}

		this.shippingNumber.add(shippingNumber);
	}

	public boolean isEmpty() {
		if (shippingNumber == null) {
			return true;
		}

		if (shippingNumber.size() < 1) {
			return true;
		}

		return false;
	}

}
