//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.27 at 11:15:55 AM JST
//

package com.oneslogi.wms.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"kokyakuCode",
		"shukkaDate",
		"totalKosu",
		"totalKensu",
		"resultCodeList",
		"printRequestId"
})
@XmlRootElement(name = "ukewatashiDetail")
public class UkewatashiDetail {

	protected String kokyakuCode;
	protected String shukkaDate;
	protected Integer totalKosu;
	protected Integer totalKensu;
	protected ResultCodeList resultCodeList;
	protected String printRequestId;

	public String getKokyakuCode() {
		return kokyakuCode;
	}

	public String getShukkaDate() {
		return shukkaDate;
	}

	public Integer getTotalKosu() {
		return totalKosu;
	}

	public Integer getTotalKensu() {
		return totalKensu;
	}

	public void setKokyakuCode(String kokyakuCode) {
		this.kokyakuCode = kokyakuCode;
	}

	public void setShukkaDate(String shukkaDate) {
		this.shukkaDate = shukkaDate;
	}

	public void setTotalKosu(Integer totalKosu) {
		this.totalKosu = totalKosu;
	}

	public void setTotalKensu(Integer totalKensu) {
		this.totalKensu = totalKensu;
	}

	public ResultCodeList getResultCodeList() {
		if (resultCodeList == null) {
			return new ResultCodeList();
		}
		return resultCodeList;
	}

	public void setResultCodeList(ResultCodeList resultCodeList) {
		this.resultCodeList = resultCodeList;
	}

	public String getPrintRequestId() {
		return printRequestId;
	}

	public void setPrintRequestId(String printRequestId) {
		this.printRequestId = printRequestId;
	}
}
